/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpack;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcielli
 */
public class CadastrarClienteFisico extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarClienteFisico
     */
    public CadastrarClienteFisico() {
        initComponents();
        
      
    }
    
    //Abrir jInternalFrame Centralizado
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelCadClienteFisico = new javax.swing.JPanel();
        txtEndereco = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        labelTelefoneResidencial = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        labelEndereco = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelCPF = new javax.swing.JLabel();
        labelRG = new javax.swing.JLabel();
        labelTelefoneCel = new javax.swing.JLabel();
        btnCadastrarClienteFisico = new javax.swing.JButton();
        txtRG = new javax.swing.JFormattedTextField();
        txtCPF = new javax.swing.JFormattedTextField();
        txtTelefoneResidencial = new javax.swing.JFormattedTextField();
        txtTelefoneCel = new javax.swing.JFormattedTextField();

        setClosable(true);
        setResizable(true);
        setTitle("Cadastrar Cliente Físico");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelTelefoneResidencial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTelefoneResidencial.setForeground(new java.awt.Color(72, 61, 139));
        labelTelefoneResidencial.setText("Tel Residencial");

        labelNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNome.setForeground(new java.awt.Color(72, 61, 139));
        labelNome.setText("Nome");

        labelEndereco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelEndereco.setForeground(new java.awt.Color(72, 61, 139));
        labelEndereco.setText("Endereço");

        labelEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(72, 61, 139));
        labelEmail.setText("Email");

        labelCPF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCPF.setForeground(new java.awt.Color(72, 61, 139));
        labelCPF.setText("CPF");

        labelRG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelRG.setForeground(new java.awt.Color(72, 61, 139));
        labelRG.setText("RG");

        labelTelefoneCel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTelefoneCel.setForeground(new java.awt.Color(72, 61, 139));
        labelTelefoneCel.setText("Cel");

        btnCadastrarClienteFisico.setBackground(new java.awt.Color(72, 61, 139));
        btnCadastrarClienteFisico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastrarClienteFisico.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarClienteFisico.setText("Cadastrar");
        btnCadastrarClienteFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteFisicoActionPerformed(evt);
            }
        });

        try {
            txtRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtTelefoneResidencial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtTelefoneCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout panelCadClienteFisicoLayout = new javax.swing.GroupLayout(panelCadClienteFisico);
        panelCadClienteFisico.setLayout(panelCadClienteFisicoLayout);
        panelCadClienteFisicoLayout.setHorizontalGroup(
            panelCadClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadClienteFisicoLayout.createSequentialGroup()
                .addGroup(panelCadClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadClienteFisicoLayout.createSequentialGroup()
                        .addGap(585, 585, 585)
                        .addComponent(btnCadastrarClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCadClienteFisicoLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(panelCadClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCadClienteFisicoLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(labelRG))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCadClienteFisicoLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(labelEndereco))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCadClienteFisicoLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(labelNome))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCadClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelEmail)
                                .addComponent(labelTelefoneResidencial)))
                        .addGroup(panelCadClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCadClienteFisicoLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(txtEmail))
                            .addGroup(panelCadClienteFisicoLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(panelCadClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEndereco, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNome)
                                    .addGroup(panelCadClienteFisicoLayout.createSequentialGroup()
                                        .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(labelCPF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCPF))))
                            .addGroup(panelCadClienteFisicoLayout.createSequentialGroup()
                                .addGap(0, 10, Short.MAX_VALUE)
                                .addComponent(txtTelefoneResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addComponent(labelTelefoneCel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTelefoneCel, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(65, 65, 65))
        );
        panelCadClienteFisicoLayout.setVerticalGroup(
            panelCadClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadClienteFisicoLayout.createSequentialGroup()
                .addGroup(panelCadClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelCadClienteFisicoLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelCadClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelCPF)
                            .addComponent(txtRG, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(txtCPF))
                        .addGap(18, 18, 18)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelCadClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelTelefoneCel)
                            .addComponent(txtTelefoneResidencial, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(txtTelefoneCel))
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCadClienteFisicoLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(labelNome)
                        .addGap(31, 31, 31)
                        .addComponent(labelRG)
                        .addGap(31, 31, 31)
                        .addComponent(labelEndereco)
                        .addGap(31, 31, 31)
                        .addComponent(labelTelefoneResidencial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelEmail)))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarClienteFisico)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCadClienteFisico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCadClienteFisico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarClienteFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteFisicoActionPerformed
                        //faz conexão com o driver
        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.print("Driver Conectado");
        //variavel de conecção
        Connection con;
        con = DriverManager.getConnection( "jdbc:mysql://127.0.0.1/transpack","root","");
        //insere valor no banco
        String query = "INSERT INTO cadastrarclientefisico (nomecf,emailcf,endcf,cpfcf,telrescf,telcelcf,rgcf) VALUES (?,?,?,?,?,?,?)";
        //prepara a entrada de dados
        PreparedStatement stmt = (PreparedStatement) con.prepareStatement(query);

        //pega os valores para inserção
        stmt.setString(1,txtNome.getText());
        stmt.setString(2,txtEmail.getText()); 
        stmt.setString(3,txtEndereco.getText());
        stmt.setString(4,txtCPF.getText());
        stmt.setString(5,txtTelefoneCel.getText());
        stmt.setString(6,txtTelefoneResidencial.getText());
        stmt.setString(7,txtRG.getText());
        
                    
      JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso");
        

        //atualiza os dados
        stmt.executeUpdate();
        
        //fecha conexão
        stmt.close();
        con.close();
        
        
        
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        System.out.print("Falha na conexão com Driver");
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        //catch de conexão com banco de dados
        System.out.print("Erro de conexão com Banco de dados");
        }
    }//GEN-LAST:event_btnCadastrarClienteFisicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarClienteFisico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelRG;
    private javax.swing.JLabel labelTelefoneCel;
    private javax.swing.JLabel labelTelefoneResidencial;
    private javax.swing.JPanel panelCadClienteFisico;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtRG;
    private javax.swing.JFormattedTextField txtTelefoneCel;
    private javax.swing.JFormattedTextField txtTelefoneResidencial;
    // End of variables declaration//GEN-END:variables
}
