/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpack;

import java.awt.Color;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Dimension;

/**
 *
 * @author Marcielli
 */
public class CadastrarClienteJuridico extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarClienteJuridico
     */
    public CadastrarClienteJuridico() {
        initComponents();
    }
    
    //Abrir jInternalFrame Centralizado
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelCadClienteJuridico = new javax.swing.JPanel();
        txtRamal = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        labelTelefone = new javax.swing.JLabel();
        txtNomeFantasia = new javax.swing.JTextField();
        labelNomeFantasia = new javax.swing.JLabel();
        labelRamal = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelNomeContato = new javax.swing.JLabel();
        txtNomeContato = new javax.swing.JTextField();
        labelCNPJ = new javax.swing.JLabel();
        labelTipoDeServicoProduto = new javax.swing.JLabel();
        txtTipoDeServicoProduto = new javax.swing.JTextField();
        btnCadastrarClienteJuridico = new javax.swing.JButton();
        txtCNPJ = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();

        setClosable(true);
        setResizable(true);
        setTitle("Cadastrar Cliente Jurídico");
        setPreferredSize(new java.awt.Dimension(800, 524));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCadClienteJuridico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelCadClienteJuridico.add(txtRamal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 250, 30));
        panelCadClienteJuridico.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 640, 30));

        labelTelefone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTelefone.setForeground(new java.awt.Color(72, 61, 139));
        labelTelefone.setText("Telefone");
        panelCadClienteJuridico.add(labelTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));
        panelCadClienteJuridico.add(txtNomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 640, 30));

        labelNomeFantasia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNomeFantasia.setForeground(new java.awt.Color(72, 61, 139));
        labelNomeFantasia.setText("Nome Fantasia");
        panelCadClienteJuridico.add(labelNomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        labelRamal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelRamal.setForeground(new java.awt.Color(72, 61, 139));
        labelRamal.setText("RAMAL");
        panelCadClienteJuridico.add(labelRamal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        labelEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(72, 61, 139));
        labelEmail.setText("Email");
        panelCadClienteJuridico.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        labelNomeContato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNomeContato.setForeground(new java.awt.Color(72, 61, 139));
        labelNomeContato.setText("Nome Contato");
        panelCadClienteJuridico.add(labelNomeContato, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, -1, -1));
        panelCadClienteJuridico.add(txtNomeContato, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 250, 30));

        labelCNPJ.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCNPJ.setForeground(new java.awt.Color(72, 61, 139));
        labelCNPJ.setText("CNPJ");
        panelCadClienteJuridico.add(labelCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        labelTipoDeServicoProduto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTipoDeServicoProduto.setForeground(new java.awt.Color(72, 61, 139));
        labelTipoDeServicoProduto.setText("Tipo de Serviço/Produto");
        panelCadClienteJuridico.add(labelTipoDeServicoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));
        panelCadClienteJuridico.add(txtTipoDeServicoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 640, 30));

        btnCadastrarClienteJuridico.setBackground(new java.awt.Color(72, 61, 139));
        btnCadastrarClienteJuridico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastrarClienteJuridico.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarClienteJuridico.setText("Cadastrar");
        btnCadastrarClienteJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteJuridicoActionPerformed(evt);
            }
        });
        panelCadClienteJuridico.add(btnCadastrarClienteJuridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, 145, -1));

        try {
            txtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        panelCadClienteJuridico.add(txtCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 250, 30));

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        panelCadClienteJuridico.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 250, 30));

        jPanel1.add(panelCadClienteJuridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 590));

        setBounds(0, 0, 1057, 614);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarClienteJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteJuridicoActionPerformed
        //faz conexão com o driver
        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.print("Driver Conectado");
        //variavel de conecção
        Connection con;
        con = DriverManager.getConnection( "jdbc:mysql://127.0.0.1/transpack","root","");
        //insere valor no banco
        String query = "INSERT INTO cadastrarclientejuridico (cnpj,email,nomecontato,nomefantasia,ramal,tel,tiposerviço) VALUES (?,?,?,?,?,?,?)";
        //prepara a entrada de dados
        PreparedStatement stmt = (PreparedStatement) con.prepareStatement(query);

        //pega os valores para inserção
        stmt.setString(1,txtCNPJ.getText());
        stmt.setString(2,txtEmail.getText()); 
        stmt.setString(3,txtNomeContato.getText());
        stmt.setString(4,txtNomeFantasia.getText());
        stmt.setString(5,txtRamal.getText());
        stmt.setString(6,txtTelefone.getText());
        stmt.setString(7,txtTipoDeServicoProduto.getText());
        
                    
     JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso");
        

        //atualiza os dados
        stmt.executeUpdate();
        
        //fecha conexão
        stmt.close();
        con.close();
        
        
        
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        System.out.print("Falha na conexão com Driver");
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        //catch de conexão com banco de dados
        System.out.print("Erro de conexão com Banco de dados");
        }
    }//GEN-LAST:event_btnCadastrarClienteJuridicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarClienteJuridico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCNPJ;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNomeContato;
    private javax.swing.JLabel labelNomeFantasia;
    private javax.swing.JLabel labelRamal;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelTipoDeServicoProduto;
    private javax.swing.JPanel panelCadClienteJuridico;
    private javax.swing.JFormattedTextField txtCNPJ;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNomeContato;
    private javax.swing.JTextField txtNomeFantasia;
    private javax.swing.JTextField txtRamal;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtTipoDeServicoProduto;
    // End of variables declaration//GEN-END:variables
}
