/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpack;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcielli
 */
public class CadastrarEquipamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarEquipamento
     */
    public CadastrarEquipamento() {
        initComponents();
    }
    
    //Abrir jInternalFrame Centralizado
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelCadEquipamento = new javax.swing.JPanel();
        labelTipo = new javax.swing.JLabel();
        txtNdeIdentificacao = new javax.swing.JTextField();
        labelAreaPertencente = new javax.swing.JLabel();
        txtAreaPertence = new javax.swing.JTextField();
        labelNdeInscricao = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        labelAreaPertencente1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDescricao = new javax.swing.JTextArea();
        btnCadastrarEquipamento = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastrar Equipamento");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTipo.setForeground(new java.awt.Color(72, 61, 139));
        labelTipo.setText("Tipo");

        labelAreaPertencente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelAreaPertencente.setForeground(new java.awt.Color(72, 61, 139));
        labelAreaPertencente.setText("Área Pertencente");

        labelNdeInscricao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNdeInscricao.setForeground(new java.awt.Color(72, 61, 139));
        labelNdeInscricao.setText("N° de Identificação");

        labelAreaPertencente1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelAreaPertencente1.setForeground(new java.awt.Color(72, 61, 139));
        labelAreaPertencente1.setText("Descrição");

        txtAreaDescricao.setColumns(20);
        txtAreaDescricao.setRows(5);
        jScrollPane1.setViewportView(txtAreaDescricao);

        btnCadastrarEquipamento.setBackground(new java.awt.Color(72, 61, 139));
        btnCadastrarEquipamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastrarEquipamento.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarEquipamento.setText("Cadastrar");
        btnCadastrarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarEquipamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCadEquipamentoLayout = new javax.swing.GroupLayout(panelCadEquipamento);
        panelCadEquipamento.setLayout(panelCadEquipamentoLayout);
        panelCadEquipamentoLayout.setHorizontalGroup(
            panelCadEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadEquipamentoLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(panelCadEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCadastrarEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCadEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelCadEquipamentoLayout.createSequentialGroup()
                            .addGroup(panelCadEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelCadEquipamentoLayout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(labelAreaPertencente))
                                .addComponent(labelAreaPertencente1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, 18)
                            .addGroup(panelCadEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAreaPertence)
                                .addComponent(jScrollPane1)))
                        .addGroup(panelCadEquipamentoLayout.createSequentialGroup()
                            .addGroup(panelCadEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelTipo)
                                .addComponent(labelNdeInscricao))
                            .addGap(10, 10, 10)
                            .addGroup(panelCadEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTipo)
                                .addComponent(txtNdeIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        panelCadEquipamentoLayout.setVerticalGroup(
            panelCadEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadEquipamentoLayout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(panelCadEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipo)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panelCadEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNdeInscricao)
                    .addComponent(txtNdeIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCadEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAreaPertence, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAreaPertencente))
                .addGap(18, 18, 18)
                .addGroup(panelCadEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAreaPertencente1))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarEquipamento)
                .addGap(126, 126, 126))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCadEquipamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCadEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarEquipamentoActionPerformed
                       //faz conexão com o driver
        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.print("Driver Conectado");
        //variavel de conecção
        Connection con;
        con = DriverManager.getConnection( "jdbc:mysql://127.0.0.1/transpack","root","");
        //insere valor no banco
        String query = "INSERT INTO cadastrarfuncionario (txtAreaDescricao,txtTipo,txtNdeIdentificacao,txtAreaPertence) VALUES (?,?,?,?)";
        //prepara a entrada de dados
        PreparedStatement stmt = (PreparedStatement) con.prepareStatement(query);

        //pega os valores para inserção
        stmt.setString(1,txtAreaDescricao.getText());
        stmt.setString(2,txtAreaPertence.getText()); 
        stmt.setString(3,txtNdeIdentificacao.getText());
        stmt.setString(4,txtTipo.getText());
       
        
      JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso");
        

        //atualiza os dados
        stmt.executeUpdate();
        
        //fecha conexão
        stmt.close();
        con.close();
        
        
        
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        System.out.print("Falha na conexão com Driver");
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        //catch de conexão com banco de dados
        System.out.print("Erro de conexão com Banco de dados");
        }
    }//GEN-LAST:event_btnCadastrarEquipamentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarEquipamento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAreaPertencente;
    private javax.swing.JLabel labelAreaPertencente1;
    private javax.swing.JLabel labelNdeInscricao;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JPanel panelCadEquipamento;
    private javax.swing.JTextArea txtAreaDescricao;
    private javax.swing.JTextField txtAreaPertence;
    private javax.swing.JTextField txtNdeIdentificacao;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
