/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpack;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcielli
 */
public class CadastrarCarga extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarCarga
     */
    public CadastrarCarga() {
        initComponents();
    }
    
    //Abrir jInternalFrame Centralizado
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelConteudo = new javax.swing.JLabel();
        txtConteudo = new javax.swing.JTextField();
        labelPeso = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        labelVeiculo = new javax.swing.JLabel();
        txtVeiculo = new javax.swing.JTextField();
        labelNPedido = new javax.swing.JLabel();
        txtPedido = new javax.swing.JTextField();
        btnCadastrarClienteFisico = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastrar Carga");

        labelConteudo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelConteudo.setForeground(new java.awt.Color(72, 61, 139));
        labelConteudo.setText("Conteúdo");

        labelPeso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPeso.setForeground(new java.awt.Color(72, 61, 139));
        labelPeso.setText("Peso");

        labelVeiculo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelVeiculo.setForeground(new java.awt.Color(72, 61, 139));
        labelVeiculo.setText("Veículo");

        labelNPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNPedido.setForeground(new java.awt.Color(72, 61, 139));
        labelNPedido.setText("N° Pedido");

        btnCadastrarClienteFisico.setBackground(new java.awt.Color(72, 61, 139));
        btnCadastrarClienteFisico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastrarClienteFisico.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarClienteFisico.setText("Cadastrar");
        btnCadastrarClienteFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteFisicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(labelConteudo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelPeso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(labelVeiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCadastrarClienteFisico)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelNPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(169, 169, 169))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelConteudo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPeso))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelVeiculo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNPedido))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarClienteFisico)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1057, 614);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarClienteFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteFisicoActionPerformed
   JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso");
    }//GEN-LAST:event_btnCadastrarClienteFisicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarClienteFisico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelConteudo;
    private javax.swing.JLabel labelNPedido;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JLabel labelVeiculo;
    private javax.swing.JTextField txtConteudo;
    private javax.swing.JTextField txtPedido;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtVeiculo;
    // End of variables declaration//GEN-END:variables
}
