/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpack;
import java.awt.Color;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.awt.Dimension;

/**
 *
 * @author Marcielli
 */
public class CadastrarVendasEServicos extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarVendasEServicos
     */
    public CadastrarVendasEServicos() {
        initComponents();
    }
    
    //Abrir jInternalFrame Centralizado
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCliente = new javax.swing.JTextField();
        labelCliente = new javax.swing.JLabel();
        txtRegistroVendasServicos = new javax.swing.JTextField();
        labelRegistroVendasServicos = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        labelTipo = new javax.swing.JLabel();
        labelNIdentidade = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        labelDestino = new javax.swing.JLabel();
        txtRemetente = new javax.swing.JTextField();
        labelRemetente = new javax.swing.JLabel();
        labeValor = new javax.swing.JLabel();
        labelVolumes = new javax.swing.JLabel();
        txtVolumes = new javax.swing.JTextField();
        btnCadastrarClienteFisico = new javax.swing.JButton();
        txtNIdentidade = new javax.swing.JFormattedTextField();
        txtValor = new javax.swing.JFormattedTextField();

        setClosable(true);
        setTitle("Cadastrar Vendas e Serviços");

        labelCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCliente.setForeground(new java.awt.Color(72, 61, 139));
        labelCliente.setText("Cliente");

        labelRegistroVendasServicos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelRegistroVendasServicos.setForeground(new java.awt.Color(72, 61, 139));
        labelRegistroVendasServicos.setText("Registro de Vendas / Serviços");

        labelTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTipo.setForeground(new java.awt.Color(72, 61, 139));
        labelTipo.setText("Tipo");

        labelNIdentidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNIdentidade.setForeground(new java.awt.Color(72, 61, 139));
        labelNIdentidade.setText("N° Identidade");

        labelDestino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelDestino.setForeground(new java.awt.Color(72, 61, 139));
        labelDestino.setText("Destino");

        labelRemetente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelRemetente.setForeground(new java.awt.Color(72, 61, 139));
        labelRemetente.setText("Remetente");

        labeValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeValor.setForeground(new java.awt.Color(72, 61, 139));
        labeValor.setText("Valor");

        labelVolumes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelVolumes.setForeground(new java.awt.Color(72, 61, 139));
        labelVolumes.setText("Volumes");

        btnCadastrarClienteFisico.setBackground(new java.awt.Color(72, 61, 139));
        btnCadastrarClienteFisico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastrarClienteFisico.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarClienteFisico.setText("Cadastrar");
        btnCadastrarClienteFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteFisicoActionPerformed(evt);
            }
        });

        try {
            txtNIdentidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$ #.###,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCadastrarClienteFisico)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelRemetente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(labeValor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(labelVolumes)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtVolumes, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(151, 151, 151)
                            .addComponent(labelCliente)
                            .addGap(18, 18, 18)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelRegistroVendasServicos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtRegistroVendasServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addComponent(labelNIdentidade)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRegistroVendasServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRegistroVendasServicos))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTipo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNIdentidade)
                    .addComponent(txtNIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDestino))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRemetente))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtVolumes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelVolumes))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarClienteFisico)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarClienteFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteFisicoActionPerformed
     //faz conexão com o driver
        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.print("Driver Conectado");
        //variavel de conecção
        Connection con;
        con = DriverManager.getConnection( "jdbc:mysql://127.0.0.1/transpack","root","");
        //insere valor no banco
        String query = "INSERT INTO vendaseservicos (cliente1,destino,reg_vendaseservicos,remetente,tipo,valor,volumes) VALUES (?,?,?,?,?,?,?)";
        //prepara a entrada de dados
        PreparedStatement stmt = (PreparedStatement) con.prepareStatement(query);

        //pega os valores para inserção
        stmt.setString(1,txtCliente.getText());
        stmt.setString(2,txtDestino.getText()); 
        stmt.setString(3,txtRegistroVendasServicos.getText());
        stmt.setString(5,txtTipo.getText());
        stmt.setString(4,txtRemetente.getText());        
        stmt.setString(6,txtValor.getText());
        stmt.setString(7,txtVolumes.getText());
       // stmt.setString(8,"");
       // stmt.setString(9,"");
        
        
                    
      JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso");
        

        //atualiza os dados
        stmt.executeUpdate();
        
        //fecha conexão
        stmt.close();
        con.close();
        
        
        
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        System.out.print("Falha na conexão com Driver");
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        //catch de conexão com banco de dados
        System.out.print("Erro de conexão com Banco de dados");
        } 
    }//GEN-LAST:event_btnCadastrarClienteFisicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarClienteFisico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labeValor;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JLabel labelNIdentidade;
    private javax.swing.JLabel labelRegistroVendasServicos;
    private javax.swing.JLabel labelRemetente;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLabel labelVolumes;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JFormattedTextField txtNIdentidade;
    private javax.swing.JTextField txtRegistroVendasServicos;
    private javax.swing.JTextField txtRemetente;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JFormattedTextField txtValor;
    private javax.swing.JTextField txtVolumes;
    // End of variables declaration//GEN-END:variables
}
