/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpack;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcielli
 */
public class CadastrarFuncionarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarFuncionarios
     */
    public CadastrarFuncionarios() {
        initComponents();
    }
    
    //Abrir jInternalFrame Centralizado
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labeNPedido = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        labeNPedido1 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        labeNPedido2 = new javax.swing.JLabel();
        txtNPedido2 = new javax.swing.JTextField();
        cpf = new javax.swing.JTextField();
        labeNPedido3 = new javax.swing.JLabel();
        orgaoemissor = new javax.swing.JTextField();
        labeNPedido4 = new javax.swing.JLabel();
        rg = new javax.swing.JTextField();
        labeNPedido5 = new javax.swing.JLabel();
        cel = new javax.swing.JTextField();
        labeNPedido6 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        labeNPedido7 = new javax.swing.JLabel();
        labeNPedido8 = new javax.swing.JLabel();
        end = new javax.swing.JTextField();
        labeNPedido9 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        cargo = new javax.swing.JTextField();
        labeNPedido10 = new javax.swing.JLabel();
        funcao = new javax.swing.JTextField();
        labeNPedido11 = new javax.swing.JLabel();
        labeNPedido12 = new javax.swing.JLabel();
        inicioContrato = new javax.swing.JTextField();
        labeNPedido13 = new javax.swing.JLabel();
        fimContrato = new javax.swing.JTextField();
        btnCadastrarFuncionario = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastrar Funcionários");

        labeNPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeNPedido.setForeground(new java.awt.Color(72, 61, 139));
        labeNPedido.setText("Código");

        labeNPedido1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeNPedido1.setForeground(new java.awt.Color(72, 61, 139));
        labeNPedido1.setText("Nome");

        labeNPedido2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeNPedido2.setForeground(new java.awt.Color(72, 61, 139));
        labeNPedido2.setText("Data de Nascimento");

        labeNPedido3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeNPedido3.setForeground(new java.awt.Color(72, 61, 139));
        labeNPedido3.setText("CPF");

        labeNPedido4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeNPedido4.setForeground(new java.awt.Color(72, 61, 139));
        labeNPedido4.setText("Orgão Emissor");

        labeNPedido5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeNPedido5.setForeground(new java.awt.Color(72, 61, 139));
        labeNPedido5.setText("RG");

        labeNPedido6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeNPedido6.setForeground(new java.awt.Color(72, 61, 139));
        labeNPedido6.setText("Tel");

        labeNPedido7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeNPedido7.setForeground(new java.awt.Color(72, 61, 139));
        labeNPedido7.setText("Cel");

        labeNPedido8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeNPedido8.setForeground(new java.awt.Color(72, 61, 139));
        labeNPedido8.setText("Endereço");

        labeNPedido9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeNPedido9.setForeground(new java.awt.Color(72, 61, 139));
        labeNPedido9.setText("Email");

        labeNPedido10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeNPedido10.setForeground(new java.awt.Color(72, 61, 139));
        labeNPedido10.setText("Cargo");

        labeNPedido11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeNPedido11.setForeground(new java.awt.Color(72, 61, 139));
        labeNPedido11.setText("Função");

        labeNPedido12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeNPedido12.setForeground(new java.awt.Color(72, 61, 139));
        labeNPedido12.setText("Data de Admissão");

        labeNPedido13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeNPedido13.setForeground(new java.awt.Color(72, 61, 139));
        labeNPedido13.setText("Data de Demissão");

        btnCadastrarFuncionario.setBackground(new java.awt.Color(72, 61, 139));
        btnCadastrarFuncionario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastrarFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarFuncionario.setText("Cadastrar");
        btnCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCadastrarFuncionario)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labeNPedido8)
                        .addGap(18, 18, 18)
                        .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labeNPedido)
                        .addGap(18, 18, 18)
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labeNPedido1)
                        .addGap(18, 18, 18)
                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labeNPedido5)
                                .addGap(18, 18, 18)
                                .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labeNPedido2)
                                .addGap(18, 18, 18)
                                .addComponent(txtNPedido2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labeNPedido6)
                                .addGap(18, 18, 18)
                                .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labeNPedido3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labeNPedido4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(orgaoemissor, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labeNPedido7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labeNPedido10)
                            .addComponent(labeNPedido9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labeNPedido11)
                                .addGap(18, 18, 18)
                                .addComponent(funcao, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labeNPedido12)
                        .addGap(18, 18, 18)
                        .addComponent(inicioContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(labeNPedido13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fimContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeNPedido))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeNPedido1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeNPedido2)
                    .addComponent(txtNPedido2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeNPedido3)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labeNPedido5)
                            .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(labeNPedido4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orgaoemissor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labeNPedido6)
                        .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(labeNPedido7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeNPedido8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeNPedido9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeNPedido10)
                    .addComponent(funcao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeNPedido11))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(inicioContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fimContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labeNPedido12)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(labeNPedido13)))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarFuncionario)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFuncionarioActionPerformed
                         //faz conexão com o driver
        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.print("Driver Conectado");
        //variavel de conecção
        Connection con;
        con = DriverManager.getConnection( "jdbc:mysql://127.0.0.1/transpack","root","");
        //insere valor no banco
        String query = "INSERT INTO cadastrarfuncionario (cargo,cel,cpf,fimContrato,inicioContrato,nome,rg.tel) VALUES (?,?,?,?,?,?,?,?)";
        //prepara a entrada de dados
        PreparedStatement stmt = (PreparedStatement) con.prepareStatement(query);

        //pega os valores para inserção
        stmt.setString(1,cargo.getText());
        stmt.setString(2,cel.getText()); 
        stmt.setString(3,cpf.getText());
        stmt.setString(4,fimContrato.getText());
        stmt.setString(5,inicioContrato.getText());
        stmt.setString(6,nome.getText());
        stmt.setString(7,rg.getText());
        stmt.setString(8,tel.getText());
                    
      JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso");
        

        //atualiza os dados
        stmt.executeUpdate();
        
        //fecha conexão
        stmt.close();
        con.close();
        
        
        
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        System.out.print("Falha na conexão com Driver");
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        //catch de conexão com banco de dados
        System.out.print("Erro de conexão com Banco de dados");
        }
                                                             
    }//GEN-LAST:event_btnCadastrarFuncionarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarFuncionario;
    private javax.swing.JTextField cargo;
    private javax.swing.JTextField cel;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField email;
    private javax.swing.JTextField end;
    private javax.swing.JTextField fimContrato;
    private javax.swing.JTextField funcao;
    private javax.swing.JTextField inicioContrato;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labeNPedido;
    private javax.swing.JLabel labeNPedido1;
    private javax.swing.JLabel labeNPedido10;
    private javax.swing.JLabel labeNPedido11;
    private javax.swing.JLabel labeNPedido12;
    private javax.swing.JLabel labeNPedido13;
    private javax.swing.JLabel labeNPedido2;
    private javax.swing.JLabel labeNPedido3;
    private javax.swing.JLabel labeNPedido4;
    private javax.swing.JLabel labeNPedido5;
    private javax.swing.JLabel labeNPedido6;
    private javax.swing.JLabel labeNPedido7;
    private javax.swing.JLabel labeNPedido8;
    private javax.swing.JLabel labeNPedido9;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField orgaoemissor;
    private javax.swing.JTextField rg;
    private javax.swing.JTextField tel;
    private javax.swing.JTextField txtNPedido2;
    // End of variables declaration//GEN-END:variables
}
