/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpack;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcielli
 */
public class CadastrarContasAReceber extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarContasAReceber
     */
    public CadastrarContasAReceber() {
        initComponents();
    }
    
    //Abrir jInternalFrame Centralizado
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCliente = new javax.swing.JTextField();
        btnCadastrarContasAReceber = new javax.swing.JButton();
        txtVencimento = new javax.swing.JTextField();
        labelVencimento = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        labelValor = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setTitle("Cadastrar Contas a Receber");

        btnCadastrarContasAReceber.setBackground(new java.awt.Color(72, 61, 139));
        btnCadastrarContasAReceber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastrarContasAReceber.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarContasAReceber.setText("Cadastrar");
        btnCadastrarContasAReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarContasAReceberActionPerformed(evt);
            }
        });

        labelVencimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelVencimento.setForeground(new java.awt.Color(72, 61, 139));
        labelVencimento.setText("Vencimento");

        labelValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelValor.setForeground(new java.awt.Color(72, 61, 139));
        labelValor.setText("Valor");

        labelCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCliente.setForeground(new java.awt.Color(72, 61, 139));
        labelCliente.setText("Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(705, 705, 705)
                        .addComponent(btnCadastrarContasAReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCliente)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(labelVencimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtVencimento))
                            .addComponent(txtCliente))))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(labelCliente)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelValor))
                        .addComponent(txtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelVencimento))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarContasAReceber)
                .addGap(228, 228, 228))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarContasAReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarContasAReceberActionPerformed
JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso");    
    }//GEN-LAST:event_btnCadastrarContasAReceberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarContasAReceber;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelValor;
    private javax.swing.JLabel labelVencimento;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtVencimento;
    // End of variables declaration//GEN-END:variables
}
