/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpack;

import java.awt.Dimension;

/**
 *
 * @author Marcielli
 */
public class ConsultarVeiculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarVeiculo
     */
    public ConsultarVeiculo() {
        initComponents();
    }
    
    //Abrir jInternalFrame Centralizado
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelConsultarVeiculo = new javax.swing.JPanel();
        txtPlaca = new javax.swing.JTextField();
        labelTipo = new javax.swing.JLabel();
        txtNdeIdentificacao = new javax.swing.JTextField();
        labelMarca = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        labelModelo = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        labelPlaca = new javax.swing.JLabel();
        labelNdeInscricao = new javax.swing.JLabel();
        labelCor = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();
        jPanelBGConsultarVeiculo1 = new javax.swing.JPanel();
        btnAlterarVeiculo = new javax.swing.JButton();
        btnExcluirVeiculo = new javax.swing.JButton();
        jPanelBGConsultarVeiculo2 = new javax.swing.JPanel();
        btnConsultarVeiculo = new javax.swing.JButton();
        btnNovaConsultarVeiculo = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Consultar Veículo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelConsultarVeiculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelConsultarVeiculo.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 632, 30));

        labelTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTipo.setForeground(new java.awt.Color(72, 61, 139));
        labelTipo.setText("Tipo");
        panelConsultarVeiculo.add(labelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));
        panelConsultarVeiculo.add(txtNdeIdentificacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 250, 30));

        labelMarca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelMarca.setForeground(new java.awt.Color(72, 61, 139));
        labelMarca.setText("Marca");
        panelConsultarVeiculo.add(labelMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));
        panelConsultarVeiculo.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 632, 30));

        labelModelo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelModelo.setForeground(new java.awt.Color(72, 61, 139));
        labelModelo.setText("Modelo");
        panelConsultarVeiculo.add(labelModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));
        panelConsultarVeiculo.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 632, 30));

        labelPlaca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPlaca.setForeground(new java.awt.Color(72, 61, 139));
        labelPlaca.setText("Placa");
        panelConsultarVeiculo.add(labelPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        labelNdeInscricao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNdeInscricao.setForeground(new java.awt.Color(72, 61, 139));
        labelNdeInscricao.setText("N° de Identificação");
        panelConsultarVeiculo.add(labelNdeInscricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        labelCor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCor.setForeground(new java.awt.Color(72, 61, 139));
        labelCor.setText("Cor");
        panelConsultarVeiculo.add(labelCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));
        panelConsultarVeiculo.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 250, 30));
        panelConsultarVeiculo.add(txtCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 632, 30));

        jPanelBGConsultarVeiculo1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 61, 139), 1, true));
        jPanelBGConsultarVeiculo1.setForeground(new java.awt.Color(72, 61, 139));

        btnAlterarVeiculo.setBackground(new java.awt.Color(72, 61, 139));
        btnAlterarVeiculo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterarVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarVeiculo.setText("Alterar");

        btnExcluirVeiculo.setBackground(new java.awt.Color(72, 61, 139));
        btnExcluirVeiculo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluirVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirVeiculo.setText("Excluir");

        javax.swing.GroupLayout jPanelBGConsultarVeiculo1Layout = new javax.swing.GroupLayout(jPanelBGConsultarVeiculo1);
        jPanelBGConsultarVeiculo1.setLayout(jPanelBGConsultarVeiculo1Layout);
        jPanelBGConsultarVeiculo1Layout.setHorizontalGroup(
            jPanelBGConsultarVeiculo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGConsultarVeiculo1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBGConsultarVeiculo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelBGConsultarVeiculo1Layout.setVerticalGroup(
            jPanelBGConsultarVeiculo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGConsultarVeiculo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAlterarVeiculo)
                .addGap(17, 17, 17)
                .addComponent(btnExcluirVeiculo)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelConsultarVeiculo.add(jPanelBGConsultarVeiculo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, 140, 90));

        jPanelBGConsultarVeiculo2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 61, 139), 1, true));
        jPanelBGConsultarVeiculo2.setForeground(new java.awt.Color(72, 61, 139));

        btnConsultarVeiculo.setBackground(new java.awt.Color(72, 61, 139));
        btnConsultarVeiculo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConsultarVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarVeiculo.setText("Consultar");

        btnNovaConsultarVeiculo.setBackground(new java.awt.Color(72, 61, 139));
        btnNovaConsultarVeiculo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNovaConsultarVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovaConsultarVeiculo.setText("Nova Consulta");

        javax.swing.GroupLayout jPanelBGConsultarVeiculo2Layout = new javax.swing.GroupLayout(jPanelBGConsultarVeiculo2);
        jPanelBGConsultarVeiculo2.setLayout(jPanelBGConsultarVeiculo2Layout);
        jPanelBGConsultarVeiculo2Layout.setHorizontalGroup(
            jPanelBGConsultarVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGConsultarVeiculo2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBGConsultarVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultarVeiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovaConsultarVeiculo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelBGConsultarVeiculo2Layout.setVerticalGroup(
            jPanelBGConsultarVeiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGConsultarVeiculo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConsultarVeiculo)
                .addGap(18, 18, 18)
                .addComponent(btnNovaConsultarVeiculo)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panelConsultarVeiculo.add(jPanelBGConsultarVeiculo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, 90));

        jPanel1.add(panelConsultarVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 1050, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarVeiculo;
    private javax.swing.JButton btnConsultarVeiculo;
    private javax.swing.JButton btnExcluirVeiculo;
    private javax.swing.JButton btnNovaConsultarVeiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBGConsultarVeiculo1;
    private javax.swing.JPanel jPanelBGConsultarVeiculo2;
    private javax.swing.JLabel labelCor;
    private javax.swing.JLabel labelMarca;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelNdeInscricao;
    private javax.swing.JLabel labelPlaca;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JPanel panelConsultarVeiculo;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNdeIdentificacao;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
