/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpack;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcielli
 */
public class ConsultarEquipamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarEquipamento
     */
    public ConsultarEquipamento() {
        initComponents();
    }

    //Abrir jInternalFrame Centralizado
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelCadEquipamento = new javax.swing.JPanel();
        labelTipo = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jPanelBGConsultarEquipamento1 = new javax.swing.JPanel();
        btnAlterarEquipamento = new javax.swing.JButton();
        btnExcluirEquipamento = new javax.swing.JButton();
        jPanelBGConsultarEquipamentor2 = new javax.swing.JPanel();
        btnNovaConsultarEquipamento = new javax.swing.JButton();
        btnConsultarEquipamento = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();

        setClosable(true);
        setResizable(true);
        setTitle("Consultar Equipamento");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTipo.setForeground(new java.awt.Color(72, 61, 139));
        labelTipo.setText("Consulta");

        jPanelBGConsultarEquipamento1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 61, 139), 1, true));
        jPanelBGConsultarEquipamento1.setForeground(new java.awt.Color(72, 61, 139));

        btnAlterarEquipamento.setBackground(new java.awt.Color(72, 61, 139));
        btnAlterarEquipamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterarEquipamento.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarEquipamento.setText("Alterar");

        btnExcluirEquipamento.setBackground(new java.awt.Color(72, 61, 139));
        btnExcluirEquipamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluirEquipamento.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirEquipamento.setText("Excluir");

        javax.swing.GroupLayout jPanelBGConsultarEquipamento1Layout = new javax.swing.GroupLayout(jPanelBGConsultarEquipamento1);
        jPanelBGConsultarEquipamento1.setLayout(jPanelBGConsultarEquipamento1Layout);
        jPanelBGConsultarEquipamento1Layout.setHorizontalGroup(
            jPanelBGConsultarEquipamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGConsultarEquipamento1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBGConsultarEquipamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterarEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelBGConsultarEquipamento1Layout.setVerticalGroup(
            jPanelBGConsultarEquipamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGConsultarEquipamento1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAlterarEquipamento)
                .addGap(17, 17, 17)
                .addComponent(btnExcluirEquipamento)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelBGConsultarEquipamentor2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 61, 139), 1, true));
        jPanelBGConsultarEquipamentor2.setForeground(new java.awt.Color(72, 61, 139));

        btnNovaConsultarEquipamento.setBackground(new java.awt.Color(72, 61, 139));
        btnNovaConsultarEquipamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNovaConsultarEquipamento.setForeground(new java.awt.Color(255, 255, 255));
        btnNovaConsultarEquipamento.setText("Nova Consulta");

        btnConsultarEquipamento.setBackground(new java.awt.Color(72, 61, 139));
        btnConsultarEquipamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConsultarEquipamento.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarEquipamento.setText("Consultar");
        btnConsultarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEquipamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBGConsultarEquipamentor2Layout = new javax.swing.GroupLayout(jPanelBGConsultarEquipamentor2);
        jPanelBGConsultarEquipamentor2.setLayout(jPanelBGConsultarEquipamentor2Layout);
        jPanelBGConsultarEquipamentor2Layout.setHorizontalGroup(
            jPanelBGConsultarEquipamentor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGConsultarEquipamentor2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBGConsultarEquipamentor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovaConsultarEquipamento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConsultarEquipamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelBGConsultarEquipamentor2Layout.setVerticalGroup(
            jPanelBGConsultarEquipamentor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGConsultarEquipamentor2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConsultarEquipamento)
                .addGap(18, 18, 18)
                .addComponent(btnNovaConsultarEquipamento)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tipo", "N° Identificação", "Área pertence", "Descrição"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Área Pertence", "N° Identificação" }));

        javax.swing.GroupLayout panelCadEquipamentoLayout = new javax.swing.GroupLayout(panelCadEquipamento);
        panelCadEquipamento.setLayout(panelCadEquipamentoLayout);
        panelCadEquipamentoLayout.setHorizontalGroup(
            panelCadEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadEquipamentoLayout.createSequentialGroup()
                .addGroup(panelCadEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadEquipamentoLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(labelTipo)
                        .addGap(34, 34, 34)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCadEquipamentoLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(panelCadEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelCadEquipamentoLayout.createSequentialGroup()
                                .addComponent(jPanelBGConsultarEquipamentor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jPanelBGConsultarEquipamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCadEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                                .addComponent(txtTipo)))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        panelCadEquipamentoLayout.setVerticalGroup(
            panelCadEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadEquipamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTipo))
                .addGap(18, 18, 18)
                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCadEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBGConsultarEquipamento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelBGConsultarEquipamentor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCadEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCadEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEquipamentoActionPerformed
   //faz conexão com o driver
        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.print("Driver Conectado");
        //variavel de conecção
        Connection con;
        con = DriverManager.getConnection( "jdbc:mysql://127.0.0.1/transpack","root","");
        //insere valor no banco
        String query = "SELECT *FROM cadastrarequipamento WHERE tipo = ?";
        //prepara a entrada de dados
        PreparedStatement stmt = (PreparedStatement) con.prepareStatement(query);

        //pega os valores para inserção
       
        stmt.setString(1,txtTipo.getText());
      
        ResultSet rs;
        rs = stmt.executeQuery();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);
        
        while (rs.next()){
            
        model.addRow(new Object[]{rs.getString("tipo"), rs.getString("n_serie"),rs.getString("area_pertence"),rs.getString("descricao")});
        
        System.out.println("Nome: " + rs.getString("tipo"));
        }
      
     

        
        
        //fecha conexão
        stmt.close();
        con.close();
         
        
        
        
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaInicio.class.getName()).log(Level.SEVERE, null, ex);
        System.out.print("Falha na conexão com Driver");
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicio.class.getName()).log(Level.SEVERE, null, ex);
        //catch de conexão com banco de dados

        } 
    }//GEN-LAST:event_btnConsultarEquipamentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarEquipamento;
    private javax.swing.JButton btnConsultarEquipamento;
    private javax.swing.JButton btnExcluirEquipamento;
    private javax.swing.JButton btnNovaConsultarEquipamento;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBGConsultarEquipamento1;
    private javax.swing.JPanel jPanelBGConsultarEquipamentor2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JPanel panelCadEquipamento;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
