/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpack;

import java.awt.Dimension;

/**
 *
 * @author Marcielli
 */
public class ConsultarFornecedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarFornecedor
     */
    public ConsultarFornecedor() {
        initComponents();
    }
    
    //Abrir jInternalFrame Centralizado
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelCadFornecedor = new javax.swing.JPanel();
        labelNomeFantasia = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtNomeFantasia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelBGConsultarClienteJuridico1 = new javax.swing.JPanel();
        btnAlterarClienteJuridico = new javax.swing.JButton();
        btnExcluirClienteJuridico = new javax.swing.JButton();
        jPanelBGConsultarClienteJuridico2 = new javax.swing.JPanel();
        btnConsultarClienteJuridico = new javax.swing.JButton();
        btnNovaConsultarClienteJuridico = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Consultar Fornecedor");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelNomeFantasia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNomeFantasia.setForeground(new java.awt.Color(72, 61, 139));
        labelNomeFantasia.setText("Consulta");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome Fantasia", "CNPJ" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome Fantasia", "CNPJ", "E-mail", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanelBGConsultarClienteJuridico1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 61, 139), 1, true));
        jPanelBGConsultarClienteJuridico1.setForeground(new java.awt.Color(72, 61, 139));

        btnAlterarClienteJuridico.setBackground(new java.awt.Color(72, 61, 139));
        btnAlterarClienteJuridico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterarClienteJuridico.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarClienteJuridico.setText("Alterar");

        btnExcluirClienteJuridico.setBackground(new java.awt.Color(72, 61, 139));
        btnExcluirClienteJuridico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluirClienteJuridico.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirClienteJuridico.setText("Excluir");

        javax.swing.GroupLayout jPanelBGConsultarClienteJuridico1Layout = new javax.swing.GroupLayout(jPanelBGConsultarClienteJuridico1);
        jPanelBGConsultarClienteJuridico1.setLayout(jPanelBGConsultarClienteJuridico1Layout);
        jPanelBGConsultarClienteJuridico1Layout.setHorizontalGroup(
            jPanelBGConsultarClienteJuridico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGConsultarClienteJuridico1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBGConsultarClienteJuridico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterarClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelBGConsultarClienteJuridico1Layout.setVerticalGroup(
            jPanelBGConsultarClienteJuridico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGConsultarClienteJuridico1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAlterarClienteJuridico)
                .addGap(17, 17, 17)
                .addComponent(btnExcluirClienteJuridico)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelBGConsultarClienteJuridico2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 61, 139), 1, true));
        jPanelBGConsultarClienteJuridico2.setForeground(new java.awt.Color(72, 61, 139));

        btnConsultarClienteJuridico.setBackground(new java.awt.Color(72, 61, 139));
        btnConsultarClienteJuridico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConsultarClienteJuridico.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarClienteJuridico.setText("Consultar");

        btnNovaConsultarClienteJuridico.setBackground(new java.awt.Color(72, 61, 139));
        btnNovaConsultarClienteJuridico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNovaConsultarClienteJuridico.setForeground(new java.awt.Color(255, 255, 255));
        btnNovaConsultarClienteJuridico.setText("Nova Consulta");

        javax.swing.GroupLayout jPanelBGConsultarClienteJuridico2Layout = new javax.swing.GroupLayout(jPanelBGConsultarClienteJuridico2);
        jPanelBGConsultarClienteJuridico2.setLayout(jPanelBGConsultarClienteJuridico2Layout);
        jPanelBGConsultarClienteJuridico2Layout.setHorizontalGroup(
            jPanelBGConsultarClienteJuridico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGConsultarClienteJuridico2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBGConsultarClienteJuridico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultarClienteJuridico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovaConsultarClienteJuridico, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelBGConsultarClienteJuridico2Layout.setVerticalGroup(
            jPanelBGConsultarClienteJuridico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGConsultarClienteJuridico2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConsultarClienteJuridico)
                .addGap(18, 18, 18)
                .addComponent(btnNovaConsultarClienteJuridico)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCadFornecedorLayout = new javax.swing.GroupLayout(panelCadFornecedor);
        panelCadFornecedor.setLayout(panelCadFornecedorLayout);
        panelCadFornecedorLayout.setHorizontalGroup(
            panelCadFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadFornecedorLayout.createSequentialGroup()
                .addContainerGap(665, Short.MAX_VALUE)
                .addComponent(jPanelBGConsultarClienteJuridico2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelBGConsultarClienteJuridico1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(panelCadFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCadFornecedorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(panelCadFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCadFornecedorLayout.createSequentialGroup()
                            .addComponent(labelNomeFantasia)
                            .addGap(19, 19, 19)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 3, Short.MAX_VALUE)))
        );
        panelCadFornecedorLayout.setVerticalGroup(
            panelCadFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadFornecedorLayout.createSequentialGroup()
                .addContainerGap(410, Short.MAX_VALUE)
                .addGroup(panelCadFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelBGConsultarClienteJuridico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelBGConsultarClienteJuridico2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
            .addGroup(panelCadFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCadFornecedorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(panelCadFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelNomeFantasia)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 219, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCadFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCadFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarClienteJuridico;
    private javax.swing.JButton btnConsultarClienteJuridico;
    private javax.swing.JButton btnExcluirClienteJuridico;
    private javax.swing.JButton btnNovaConsultarClienteJuridico;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBGConsultarClienteJuridico1;
    private javax.swing.JPanel jPanelBGConsultarClienteJuridico2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelNomeFantasia;
    private javax.swing.JPanel panelCadFornecedor;
    private javax.swing.JTextField txtNomeFantasia;
    // End of variables declaration//GEN-END:variables
}
