/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpack;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcielli
 */
public class ConsultarClienteJuridico extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarClienteJuridico
     */
    public ConsultarClienteJuridico() {
        initComponents();
    }
    
    //Abrir jInternalFrame Centralizado
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelCadClienteJuridico = new javax.swing.JPanel();
        txtpesquisa = new javax.swing.JTextField();
        labelNomeFantasia = new javax.swing.JLabel();
        jPanelBGConsultarClienteJuridico1 = new javax.swing.JPanel();
        btnAlterarClienteJuridico = new javax.swing.JButton();
        btnExcluirClienteJuridico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanelBGConsultarClienteJuridico2 = new javax.swing.JPanel();
        btnConsultarClienteJuridico = new javax.swing.JButton();
        btnNovaConsultarClienteJuridico = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Consultar Cliente Jurídico");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCadClienteJuridico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelCadClienteJuridico.add(txtpesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 900, 30));

        labelNomeFantasia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNomeFantasia.setForeground(new java.awt.Color(72, 61, 139));
        labelNomeFantasia.setText("Consulta");
        panelCadClienteJuridico.add(labelNomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jPanelBGConsultarClienteJuridico1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 61, 139), 1, true));
        jPanelBGConsultarClienteJuridico1.setForeground(new java.awt.Color(72, 61, 139));

        btnAlterarClienteJuridico.setBackground(new java.awt.Color(72, 61, 139));
        btnAlterarClienteJuridico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterarClienteJuridico.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarClienteJuridico.setText("Alterar");

        btnExcluirClienteJuridico.setBackground(new java.awt.Color(72, 61, 139));
        btnExcluirClienteJuridico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluirClienteJuridico.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirClienteJuridico.setText("Excluir");

        javax.swing.GroupLayout jPanelBGConsultarClienteJuridico1Layout = new javax.swing.GroupLayout(jPanelBGConsultarClienteJuridico1);
        jPanelBGConsultarClienteJuridico1.setLayout(jPanelBGConsultarClienteJuridico1Layout);
        jPanelBGConsultarClienteJuridico1Layout.setHorizontalGroup(
            jPanelBGConsultarClienteJuridico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGConsultarClienteJuridico1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBGConsultarClienteJuridico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterarClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelBGConsultarClienteJuridico1Layout.setVerticalGroup(
            jPanelBGConsultarClienteJuridico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGConsultarClienteJuridico1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAlterarClienteJuridico)
                .addGap(17, 17, 17)
                .addComponent(btnExcluirClienteJuridico)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelCadClienteJuridico.add(jPanelBGConsultarClienteJuridico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 400, 140, 90));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome Fantasia", "CNPJ", "E-mail", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panelCadClienteJuridico.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 900, 170));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome Fantasia", "CNPJ" }));
        panelCadClienteJuridico.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jPanelBGConsultarClienteJuridico2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 61, 139), 1, true));
        jPanelBGConsultarClienteJuridico2.setForeground(new java.awt.Color(72, 61, 139));

        btnConsultarClienteJuridico.setBackground(new java.awt.Color(72, 61, 139));
        btnConsultarClienteJuridico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConsultarClienteJuridico.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarClienteJuridico.setText("Consultar");
        btnConsultarClienteJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClienteJuridicoActionPerformed(evt);
            }
        });

        btnNovaConsultarClienteJuridico.setBackground(new java.awt.Color(72, 61, 139));
        btnNovaConsultarClienteJuridico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNovaConsultarClienteJuridico.setForeground(new java.awt.Color(255, 255, 255));
        btnNovaConsultarClienteJuridico.setText("Nova Consulta");

        javax.swing.GroupLayout jPanelBGConsultarClienteJuridico2Layout = new javax.swing.GroupLayout(jPanelBGConsultarClienteJuridico2);
        jPanelBGConsultarClienteJuridico2.setLayout(jPanelBGConsultarClienteJuridico2Layout);
        jPanelBGConsultarClienteJuridico2Layout.setHorizontalGroup(
            jPanelBGConsultarClienteJuridico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGConsultarClienteJuridico2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBGConsultarClienteJuridico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultarClienteJuridico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovaConsultarClienteJuridico, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelBGConsultarClienteJuridico2Layout.setVerticalGroup(
            jPanelBGConsultarClienteJuridico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGConsultarClienteJuridico2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConsultarClienteJuridico)
                .addGap(18, 18, 18)
                .addComponent(btnNovaConsultarClienteJuridico)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panelCadClienteJuridico.add(jPanelBGConsultarClienteJuridico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, -1, -1));

        jPanel1.add(panelCadClienteJuridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -5, 1050, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 479));

        setBounds(0, 0, 1057, 614);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarClienteJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClienteJuridicoActionPerformed

//faz conexão com o driver
        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.print("Driver Conectado");
        //variavel de conecção
            Connection con;
            con = DriverManager.getConnection( "jdbc:mysql://127.0.0.1/transpack","root","");

        
//String tipo = (String) jComboBox1.getSelectedItem();
//String escolha;
//if (tipo == ("Nome Fantasia")){
    //escolha = "nomefantasia";
    String query = "SELECT * FROM cadastrarclientejuridico WHERE nomefantasia LIKE ? ESCAPE '!'";
  //  }   
//else {
//String query = "SELECT *FROM cadastrarclientejuridico WHERE cnpj = ?";
//escolha = "cnpj";
//}        






//insere valor no banco
        
        //prepara a entrada de dados
        PreparedStatement stmt = (PreparedStatement) con.prepareStatement(query);

        //pega os valores para inserção
       
        stmt.setString(1,"%"  +txtpesquisa.getText());
      
        ResultSet rs;
        rs = stmt.executeQuery();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);
        
        while (rs.next()){
            
        model.addRow(new Object[]{rs.getString("nomefantasia"), rs.getString("cnpj"),rs.getString("email"),rs.getString("tel")});
        
        System.out.println("Nome: " + rs.getString("nomefantasia"));
        }
      
     

        
        
        //fecha conexão
        stmt.close();
        con.close();
         
        
        
        
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaInicio.class.getName()).log(Level.SEVERE, null, ex);
        System.out.print("Falha na conexão com Driver");
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicio.class.getName()).log(Level.SEVERE, null, ex);
        //catch de conexão com banco de dados

        } 
    }//GEN-LAST:event_btnConsultarClienteJuridicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarClienteJuridico;
    private javax.swing.JButton btnConsultarClienteJuridico;
    private javax.swing.JButton btnExcluirClienteJuridico;
    private javax.swing.JButton btnNovaConsultarClienteJuridico;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBGConsultarClienteJuridico1;
    private javax.swing.JPanel jPanelBGConsultarClienteJuridico2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelNomeFantasia;
    private javax.swing.JPanel panelCadClienteJuridico;
    private javax.swing.JTextField txtpesquisa;
    // End of variables declaration//GEN-END:variables
}
