/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpack;

import java.awt.Dimension;

/**
 *
 * @author Marcielli
 */
public class ConsultarContasAReceber extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarContasAReceber
     */
    public ConsultarContasAReceber() {
        initComponents();
    }
    
    //Abrir jInternalFrame Centralizado
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBGConsultarContasAReceber1 = new javax.swing.JPanel();
        btnAlterarContasAReceber = new javax.swing.JButton();
        btnExcluirContasAReceber = new javax.swing.JButton();
        jPanelBGConsultarContasAReceber2 = new javax.swing.JPanel();
        btnConsultarContasAReceber = new javax.swing.JButton();
        btnNovaConsultarContasAReceber = new javax.swing.JButton();
        txtVencimento = new javax.swing.JTextField();
        txtConta = new javax.swing.JTextField();
        labelVencimento = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        labelValor = new javax.swing.JLabel();
        labelConta = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setTitle("Consultar Contas a Receber");

        jPanelBGConsultarContasAReceber1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 61, 139), 1, true));
        jPanelBGConsultarContasAReceber1.setForeground(new java.awt.Color(72, 61, 139));

        btnAlterarContasAReceber.setBackground(new java.awt.Color(72, 61, 139));
        btnAlterarContasAReceber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterarContasAReceber.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarContasAReceber.setText("Alterar");

        btnExcluirContasAReceber.setBackground(new java.awt.Color(72, 61, 139));
        btnExcluirContasAReceber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluirContasAReceber.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirContasAReceber.setText("Excluir");

        javax.swing.GroupLayout jPanelBGConsultarContasAReceber1Layout = new javax.swing.GroupLayout(jPanelBGConsultarContasAReceber1);
        jPanelBGConsultarContasAReceber1.setLayout(jPanelBGConsultarContasAReceber1Layout);
        jPanelBGConsultarContasAReceber1Layout.setHorizontalGroup(
            jPanelBGConsultarContasAReceber1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGConsultarContasAReceber1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBGConsultarContasAReceber1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterarContasAReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirContasAReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelBGConsultarContasAReceber1Layout.setVerticalGroup(
            jPanelBGConsultarContasAReceber1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGConsultarContasAReceber1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAlterarContasAReceber)
                .addGap(17, 17, 17)
                .addComponent(btnExcluirContasAReceber)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelBGConsultarContasAReceber2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 61, 139), 1, true));
        jPanelBGConsultarContasAReceber2.setForeground(new java.awt.Color(72, 61, 139));

        btnConsultarContasAReceber.setBackground(new java.awt.Color(72, 61, 139));
        btnConsultarContasAReceber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConsultarContasAReceber.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarContasAReceber.setText("Consultar");

        btnNovaConsultarContasAReceber.setBackground(new java.awt.Color(72, 61, 139));
        btnNovaConsultarContasAReceber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNovaConsultarContasAReceber.setForeground(new java.awt.Color(255, 255, 255));
        btnNovaConsultarContasAReceber.setText("Nova Consulta");

        javax.swing.GroupLayout jPanelBGConsultarContasAReceber2Layout = new javax.swing.GroupLayout(jPanelBGConsultarContasAReceber2);
        jPanelBGConsultarContasAReceber2.setLayout(jPanelBGConsultarContasAReceber2Layout);
        jPanelBGConsultarContasAReceber2Layout.setHorizontalGroup(
            jPanelBGConsultarContasAReceber2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGConsultarContasAReceber2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBGConsultarContasAReceber2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultarContasAReceber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovaConsultarContasAReceber, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelBGConsultarContasAReceber2Layout.setVerticalGroup(
            jPanelBGConsultarContasAReceber2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGConsultarContasAReceber2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConsultarContasAReceber)
                .addGap(18, 18, 18)
                .addComponent(btnNovaConsultarContasAReceber)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        labelVencimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelVencimento.setForeground(new java.awt.Color(72, 61, 139));
        labelVencimento.setText("Vencimento");

        labelValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelValor.setForeground(new java.awt.Color(72, 61, 139));
        labelValor.setText("Valor");

        labelConta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelConta.setForeground(new java.awt.Color(72, 61, 139));
        labelConta.setText("Conta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelConta)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(labelVencimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtVencimento, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                    .addComponent(txtConta))
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelBGConsultarContasAReceber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelBGConsultarContasAReceber1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtConta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(labelConta)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelValor))
                        .addComponent(txtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelVencimento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBGConsultarContasAReceber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelBGConsultarContasAReceber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(161, 161, 161))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarContasAReceber;
    private javax.swing.JButton btnConsultarContasAReceber;
    private javax.swing.JButton btnExcluirContasAReceber;
    private javax.swing.JButton btnNovaConsultarContasAReceber;
    private javax.swing.JPanel jPanelBGConsultarContasAReceber1;
    private javax.swing.JPanel jPanelBGConsultarContasAReceber2;
    private javax.swing.JLabel labelConta;
    private javax.swing.JLabel labelValor;
    private javax.swing.JLabel labelVencimento;
    private javax.swing.JTextField txtConta;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtVencimento;
    // End of variables declaration//GEN-END:variables
}
