/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpack;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcielli
 */
public class ConsultarVendasEServicos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarVendasEServicos
     */
    public ConsultarVendasEServicos() {
        initComponents();
    }
    
    //Abrir jInternalFrame Centralizado
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTipoVendasEServicos = new javax.swing.JLabel();
        jComboBox1VendasEServicos = new javax.swing.JComboBox<>();
        txtpesquisa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1VendasEServicos = new javax.swing.JTable();
        jPanelBGVendasEServicos = new javax.swing.JPanel();
        btnAlterarVendasEServicos = new javax.swing.JButton();
        btnExcluirVendasEServicos = new javax.swing.JButton();
        jPanelBGConsultarEquipamentor2 = new javax.swing.JPanel();
        btnNovaConsultarEquipamento = new javax.swing.JButton();
        btnConsultarEquipamento = new javax.swing.JButton();

        setClosable(true);
        setTitle("Consultar Vendas e Serviços");

        labelTipoVendasEServicos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTipoVendasEServicos.setForeground(new java.awt.Color(72, 61, 139));
        labelTipoVendasEServicos.setText("Consulta");

        jComboBox1VendasEServicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Área Pertence", "N° Identificação" }));

        jTable1VendasEServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tipo", "N° Identificação", "Destino", "Remetente", "Valor", "Volume"
            }
        ));
        jScrollPane2.setViewportView(jTable1VendasEServicos);

        jPanelBGVendasEServicos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 61, 139), 1, true));
        jPanelBGVendasEServicos.setForeground(new java.awt.Color(72, 61, 139));

        btnAlterarVendasEServicos.setBackground(new java.awt.Color(72, 61, 139));
        btnAlterarVendasEServicos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterarVendasEServicos.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarVendasEServicos.setText("Alterar");

        btnExcluirVendasEServicos.setBackground(new java.awt.Color(72, 61, 139));
        btnExcluirVendasEServicos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluirVendasEServicos.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirVendasEServicos.setText("Excluir");

        javax.swing.GroupLayout jPanelBGVendasEServicosLayout = new javax.swing.GroupLayout(jPanelBGVendasEServicos);
        jPanelBGVendasEServicos.setLayout(jPanelBGVendasEServicosLayout);
        jPanelBGVendasEServicosLayout.setHorizontalGroup(
            jPanelBGVendasEServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGVendasEServicosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBGVendasEServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterarVendasEServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirVendasEServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelBGVendasEServicosLayout.setVerticalGroup(
            jPanelBGVendasEServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGVendasEServicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAlterarVendasEServicos)
                .addGap(17, 17, 17)
                .addComponent(btnExcluirVendasEServicos)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelBGConsultarEquipamentor2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 61, 139), 1, true));
        jPanelBGConsultarEquipamentor2.setForeground(new java.awt.Color(72, 61, 139));

        btnNovaConsultarEquipamento.setBackground(new java.awt.Color(72, 61, 139));
        btnNovaConsultarEquipamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNovaConsultarEquipamento.setForeground(new java.awt.Color(255, 255, 255));
        btnNovaConsultarEquipamento.setText("Nova Consulta");

        btnConsultarEquipamento.setBackground(new java.awt.Color(72, 61, 139));
        btnConsultarEquipamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConsultarEquipamento.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarEquipamento.setText("Consultar");
        btnConsultarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEquipamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBGConsultarEquipamentor2Layout = new javax.swing.GroupLayout(jPanelBGConsultarEquipamentor2);
        jPanelBGConsultarEquipamentor2.setLayout(jPanelBGConsultarEquipamentor2Layout);
        jPanelBGConsultarEquipamentor2Layout.setHorizontalGroup(
            jPanelBGConsultarEquipamentor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGConsultarEquipamentor2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBGConsultarEquipamentor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovaConsultarEquipamento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConsultarEquipamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelBGConsultarEquipamentor2Layout.setVerticalGroup(
            jPanelBGConsultarEquipamentor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGConsultarEquipamentor2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConsultarEquipamento)
                .addGap(18, 18, 18)
                .addComponent(btnNovaConsultarEquipamento)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                            .addComponent(txtpesquisa)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(labelTipoVendasEServicos)
                        .addGap(34, 34, 34)
                        .addComponent(jComboBox1VendasEServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelBGConsultarEquipamentor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelBGVendasEServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelBGVendasEServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1VendasEServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTipoVendasEServicos))
                        .addGap(18, 18, 18)
                        .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jPanelBGConsultarEquipamentor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEquipamentoActionPerformed
    //faz conexão com o driver
        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.print("Driver Conectado");
        //variavel de conecção
        Connection con;
        con = DriverManager.getConnection( "jdbc:mysql://127.0.0.1/transpack","root","");
        //insere valor no banco
        String query = "SELECT *FROM vendaseservicos WHERE cliente1 = ?";
        //prepara a entrada de dados
        PreparedStatement stmt = (PreparedStatement) con.prepareStatement(query);

        //pega os valores para inserção
       
        stmt.setString(1,txtpesquisa.getText());
      
        ResultSet rs;
        rs = stmt.executeQuery();
        
        DefaultTableModel model = (DefaultTableModel) jTable1VendasEServicos.getModel();
        model.setNumRows(0);
        
        while (rs.next()){
            
        model.addRow(new Object[]{rs.getString("tipo"), rs.getString("reg_vendaseservicos"),rs.getString("destino"),rs.getString("remetente"),rs.getString("valor"),rs.getString("volumes")});
        
        System.out.println("Nome: " + rs.getString("tipo"));
        }
      
     

        
        
        //fecha conexão
        stmt.close();
        con.close();
         
        
        
        
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaInicio.class.getName()).log(Level.SEVERE, null, ex);
        System.out.print("Falha na conexão com Driver");
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicio.class.getName()).log(Level.SEVERE, null, ex);
        //catch de conexão com banco de dados

        } 
    }//GEN-LAST:event_btnConsultarEquipamentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarVendasEServicos;
    private javax.swing.JButton btnConsultarEquipamento;
    private javax.swing.JButton btnExcluirVendasEServicos;
    private javax.swing.JButton btnNovaConsultarEquipamento;
    private javax.swing.JComboBox<String> jComboBox1VendasEServicos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBGConsultarEquipamentor2;
    private javax.swing.JPanel jPanelBGVendasEServicos;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1VendasEServicos;
    private javax.swing.JLabel labelTipoVendasEServicos;
    private javax.swing.JTextField txtpesquisa;
    // End of variables declaration//GEN-END:variables
}
