/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpack;

import java.awt.Dimension;

/**
 *
 * @author Marcielli
 */
public class ConsultarContasAPagar extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarContasAPagar
     */
    public ConsultarContasAPagar() {
        initComponents();
    }
    
    //Abrir jInternalFrame Centralizado
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtConta = new javax.swing.JTextField();
        txtVencimento = new javax.swing.JTextField();
        labelVencimento = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        labelValor = new javax.swing.JLabel();
        labelConta = new javax.swing.JLabel();
        jPanelBGConsultarContasAPagar1 = new javax.swing.JPanel();
        btnAlterarContasAPagar = new javax.swing.JButton();
        btnExcluirContasAPagar = new javax.swing.JButton();
        jPanelBGConsultarContasAPagar2 = new javax.swing.JPanel();
        btnConsultarContasAPagar = new javax.swing.JButton();
        btnNovaConsultarContasAPagar = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setTitle("Consultar Contas a Pagar");

        labelVencimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelVencimento.setForeground(new java.awt.Color(72, 61, 139));
        labelVencimento.setText("Vencimento");

        labelValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelValor.setForeground(new java.awt.Color(72, 61, 139));
        labelValor.setText("Valor");

        labelConta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelConta.setForeground(new java.awt.Color(72, 61, 139));
        labelConta.setText("Conta");

        jPanelBGConsultarContasAPagar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 61, 139), 1, true));
        jPanelBGConsultarContasAPagar1.setForeground(new java.awt.Color(72, 61, 139));

        btnAlterarContasAPagar.setBackground(new java.awt.Color(72, 61, 139));
        btnAlterarContasAPagar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterarContasAPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarContasAPagar.setText("Alterar");

        btnExcluirContasAPagar.setBackground(new java.awt.Color(72, 61, 139));
        btnExcluirContasAPagar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluirContasAPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirContasAPagar.setText("Excluir");

        javax.swing.GroupLayout jPanelBGConsultarContasAPagar1Layout = new javax.swing.GroupLayout(jPanelBGConsultarContasAPagar1);
        jPanelBGConsultarContasAPagar1.setLayout(jPanelBGConsultarContasAPagar1Layout);
        jPanelBGConsultarContasAPagar1Layout.setHorizontalGroup(
            jPanelBGConsultarContasAPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGConsultarContasAPagar1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBGConsultarContasAPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterarContasAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirContasAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelBGConsultarContasAPagar1Layout.setVerticalGroup(
            jPanelBGConsultarContasAPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGConsultarContasAPagar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAlterarContasAPagar)
                .addGap(17, 17, 17)
                .addComponent(btnExcluirContasAPagar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelBGConsultarContasAPagar2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 61, 139), 1, true));
        jPanelBGConsultarContasAPagar2.setForeground(new java.awt.Color(72, 61, 139));

        btnConsultarContasAPagar.setBackground(new java.awt.Color(72, 61, 139));
        btnConsultarContasAPagar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConsultarContasAPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarContasAPagar.setText("Consultar");

        btnNovaConsultarContasAPagar.setBackground(new java.awt.Color(72, 61, 139));
        btnNovaConsultarContasAPagar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNovaConsultarContasAPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnNovaConsultarContasAPagar.setText("Nova Consulta");

        javax.swing.GroupLayout jPanelBGConsultarContasAPagar2Layout = new javax.swing.GroupLayout(jPanelBGConsultarContasAPagar2);
        jPanelBGConsultarContasAPagar2.setLayout(jPanelBGConsultarContasAPagar2Layout);
        jPanelBGConsultarContasAPagar2Layout.setHorizontalGroup(
            jPanelBGConsultarContasAPagar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGConsultarContasAPagar2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBGConsultarContasAPagar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultarContasAPagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovaConsultarContasAPagar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelBGConsultarContasAPagar2Layout.setVerticalGroup(
            jPanelBGConsultarContasAPagar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGConsultarContasAPagar2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConsultarContasAPagar)
                .addGap(18, 18, 18)
                .addComponent(btnNovaConsultarContasAPagar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelConta)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(labelVencimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtVencimento, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                    .addComponent(txtConta))
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelBGConsultarContasAPagar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelBGConsultarContasAPagar1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtConta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(labelConta)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelValor))
                        .addComponent(txtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelVencimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBGConsultarContasAPagar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelBGConsultarContasAPagar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(168, 168, 168))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarContasAPagar;
    private javax.swing.JButton btnConsultarContasAPagar;
    private javax.swing.JButton btnExcluirContasAPagar;
    private javax.swing.JButton btnNovaConsultarContasAPagar;
    private javax.swing.JPanel jPanelBGConsultarContasAPagar1;
    private javax.swing.JPanel jPanelBGConsultarContasAPagar2;
    private javax.swing.JLabel labelConta;
    private javax.swing.JLabel labelValor;
    private javax.swing.JLabel labelVencimento;
    private javax.swing.JTextField txtConta;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtVencimento;
    // End of variables declaration//GEN-END:variables
}
