/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpack;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcielli
 */
public class ConsultarClienteFisico extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarClienteFisico
     */
    public ConsultarClienteFisico() {
        initComponents();
    }

    //Abrir jInternalFrame Centralizado
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelConsultarClienteFisico = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        jPanelBGConsultarClienteFisico1 = new javax.swing.JPanel();
        btnAlterarClienteFisico = new javax.swing.JButton();
        btnExcluirClienteFisico = new javax.swing.JButton();
        jPanelBGConsultarClienteFisico2 = new javax.swing.JPanel();
        btnNovaConsultarClienteFisico = new javax.swing.JButton();
        btnConsultarClienteFisico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();

        setClosable(true);
        setResizable(true);
        setTitle("Consultar Cliente Fisico");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNome.setForeground(new java.awt.Color(72, 61, 139));
        labelNome.setText("Consulta");

        jPanelBGConsultarClienteFisico1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 61, 139), 1, true));
        jPanelBGConsultarClienteFisico1.setForeground(new java.awt.Color(72, 61, 139));

        btnAlterarClienteFisico.setBackground(new java.awt.Color(72, 61, 139));
        btnAlterarClienteFisico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterarClienteFisico.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarClienteFisico.setText("Alterar");

        btnExcluirClienteFisico.setBackground(new java.awt.Color(72, 61, 139));
        btnExcluirClienteFisico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluirClienteFisico.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirClienteFisico.setText("Excluir");

        javax.swing.GroupLayout jPanelBGConsultarClienteFisico1Layout = new javax.swing.GroupLayout(jPanelBGConsultarClienteFisico1);
        jPanelBGConsultarClienteFisico1.setLayout(jPanelBGConsultarClienteFisico1Layout);
        jPanelBGConsultarClienteFisico1Layout.setHorizontalGroup(
            jPanelBGConsultarClienteFisico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGConsultarClienteFisico1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBGConsultarClienteFisico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterarClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelBGConsultarClienteFisico1Layout.setVerticalGroup(
            jPanelBGConsultarClienteFisico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGConsultarClienteFisico1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAlterarClienteFisico)
                .addGap(17, 17, 17)
                .addComponent(btnExcluirClienteFisico)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelBGConsultarClienteFisico2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 61, 139), 1, true));
        jPanelBGConsultarClienteFisico2.setForeground(new java.awt.Color(72, 61, 139));

        btnNovaConsultarClienteFisico.setBackground(new java.awt.Color(72, 61, 139));
        btnNovaConsultarClienteFisico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNovaConsultarClienteFisico.setForeground(new java.awt.Color(255, 255, 255));
        btnNovaConsultarClienteFisico.setText("Nova Consulta");

        btnConsultarClienteFisico.setBackground(new java.awt.Color(72, 61, 139));
        btnConsultarClienteFisico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConsultarClienteFisico.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarClienteFisico.setText("Consultar");
        btnConsultarClienteFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClienteFisicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBGConsultarClienteFisico2Layout = new javax.swing.GroupLayout(jPanelBGConsultarClienteFisico2);
        jPanelBGConsultarClienteFisico2.setLayout(jPanelBGConsultarClienteFisico2Layout);
        jPanelBGConsultarClienteFisico2Layout.setHorizontalGroup(
            jPanelBGConsultarClienteFisico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGConsultarClienteFisico2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNovaConsultarClienteFisico)
                .addContainerGap())
            .addGroup(jPanelBGConsultarClienteFisico2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConsultarClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBGConsultarClienteFisico2Layout.setVerticalGroup(
            jPanelBGConsultarClienteFisico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGConsultarClienteFisico2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConsultarClienteFisico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnNovaConsultarClienteFisico)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Endereço", "Telefone", "Celular", "Email"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "RG", "CPF", "E-mail" }));

        javax.swing.GroupLayout panelConsultarClienteFisicoLayout = new javax.swing.GroupLayout(panelConsultarClienteFisico);
        panelConsultarClienteFisico.setLayout(panelConsultarClienteFisicoLayout);
        panelConsultarClienteFisicoLayout.setHorizontalGroup(
            panelConsultarClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarClienteFisicoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(labelNome)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarClienteFisicoLayout.createSequentialGroup()
                .addGroup(panelConsultarClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelConsultarClienteFisicoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelBGConsultarClienteFisico2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelBGConsultarClienteFisico1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConsultarClienteFisicoLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(panelConsultarClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                            .addComponent(txtNome))))
                .addGap(57, 57, 57))
        );
        panelConsultarClienteFisicoLayout.setVerticalGroup(
            panelConsultarClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarClienteFisicoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panelConsultarClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelConsultarClienteFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBGConsultarClienteFisico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelBGConsultarClienteFisico2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConsultarClienteFisico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConsultarClienteFisico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarClienteFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClienteFisicoActionPerformed
//faz conexão com o driver
        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.print("Driver Conectado");
        //variavel de conecção
        Connection con;
        con = DriverManager.getConnection( "jdbc:mysql://127.0.0.1/transpack","root","");
        //insere valor no banco
        String query = "SELECT *FROM cadastrarclientefisico WHERE nomecf LIKE ? ESCAPE '!'";        
        //prepara a entrada de dados
        PreparedStatement stmt = (PreparedStatement) con.prepareStatement(query);

        //pega os valores para inserção
       
        stmt.setString(1, "%" + txtNome.getText());
      
        ResultSet rs;
        rs = stmt.executeQuery();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);
        
        while (rs.next()){
            
        model.addRow(new Object[]{rs.getString("nomecf"), rs.getString("endcf"),rs.getString("telrescf"),rs.getString("telcelcf"),rs.getString("emailcf")});
        
        System.out.println("Nome: " + rs.getString("nomecf"));
        }
      
     

        
        
        //fecha conexão
        stmt.close();
        con.close();
         
        
        
        
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaInicio.class.getName()).log(Level.SEVERE, null, ex);
        System.out.print("Falha na conexão com Driver");
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicio.class.getName()).log(Level.SEVERE, null, ex);
        //catch de conexão com banco de dados

        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarClienteFisicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarClienteFisico;
    private javax.swing.JButton btnConsultarClienteFisico;
    private javax.swing.JButton btnExcluirClienteFisico;
    private javax.swing.JButton btnNovaConsultarClienteFisico;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBGConsultarClienteFisico1;
    private javax.swing.JPanel jPanelBGConsultarClienteFisico2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JPanel panelConsultarClienteFisico;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
