/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpack;

import java.awt.Dimension;

/**
 *
 * @author Marcielli
 */
public class ControlarManutencao extends javax.swing.JInternalFrame {

    /**
     * Creates new form ControlarManutencao
     */
    public ControlarManutencao() {
        initComponents();
    }
    
    //Abrir jInternalFrame Centralizado
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        labelRenavam = new javax.swing.JLabel();
        txtRenavam = new javax.swing.JTextField();
        labelQuilometragem = new javax.swing.JLabel();
        txtQuilometragem = new javax.swing.JTextField();
        labelPreditiva = new javax.swing.JLabel();
        txtPreditiva = new javax.swing.JTextField();
        jPanelBGControlarManutencao1 = new javax.swing.JPanel();
        btnAlterarControleManutencao = new javax.swing.JButton();
        btnExcluirControleManutencao = new javax.swing.JButton();
        jPanelBGControlarManutencao2 = new javax.swing.JPanel();
        btnControleManutencao = new javax.swing.JButton();
        btnNovaControleManutencao = new javax.swing.JButton();
        labelPreventiva = new javax.swing.JLabel();
        txtPreventiva = new javax.swing.JTextField();
        txtPreditiva1 = new javax.swing.JTextField();
        labelPreventiva1 = new javax.swing.JLabel();
        labelOS = new javax.swing.JLabel();
        txtOS = new javax.swing.JTextField();
        labelData = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        labelPreventiva4 = new javax.swing.JLabel();
        txtPreditiva4 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Controlar Manutenção");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPlaca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPlaca.setForeground(new java.awt.Color(72, 61, 139));
        labelPlaca.setText("Placa");

        labelRenavam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelRenavam.setForeground(new java.awt.Color(72, 61, 139));
        labelRenavam.setText("Renavam");

        labelQuilometragem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelQuilometragem.setForeground(new java.awt.Color(72, 61, 139));
        labelQuilometragem.setText("Quilometragem");

        labelPreditiva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPreditiva.setForeground(new java.awt.Color(72, 61, 139));
        labelPreditiva.setText("Preditiva");

        jPanelBGControlarManutencao1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 61, 139), 1, true));
        jPanelBGControlarManutencao1.setForeground(new java.awt.Color(72, 61, 139));

        btnAlterarControleManutencao.setBackground(new java.awt.Color(72, 61, 139));
        btnAlterarControleManutencao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterarControleManutencao.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarControleManutencao.setText("Alterar");

        btnExcluirControleManutencao.setBackground(new java.awt.Color(72, 61, 139));
        btnExcluirControleManutencao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluirControleManutencao.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirControleManutencao.setText("Excluir");

        javax.swing.GroupLayout jPanelBGControlarManutencao1Layout = new javax.swing.GroupLayout(jPanelBGControlarManutencao1);
        jPanelBGControlarManutencao1.setLayout(jPanelBGControlarManutencao1Layout);
        jPanelBGControlarManutencao1Layout.setHorizontalGroup(
            jPanelBGControlarManutencao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGControlarManutencao1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBGControlarManutencao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterarControleManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirControleManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelBGControlarManutencao1Layout.setVerticalGroup(
            jPanelBGControlarManutencao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGControlarManutencao1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAlterarControleManutencao)
                .addGap(17, 17, 17)
                .addComponent(btnExcluirControleManutencao)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelBGControlarManutencao2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 61, 139), 1, true));
        jPanelBGControlarManutencao2.setForeground(new java.awt.Color(72, 61, 139));

        btnControleManutencao.setBackground(new java.awt.Color(72, 61, 139));
        btnControleManutencao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnControleManutencao.setForeground(new java.awt.Color(255, 255, 255));
        btnControleManutencao.setText("Consultar");

        btnNovaControleManutencao.setBackground(new java.awt.Color(72, 61, 139));
        btnNovaControleManutencao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNovaControleManutencao.setForeground(new java.awt.Color(255, 255, 255));
        btnNovaControleManutencao.setText("Nova Consulta");

        javax.swing.GroupLayout jPanelBGControlarManutencao2Layout = new javax.swing.GroupLayout(jPanelBGControlarManutencao2);
        jPanelBGControlarManutencao2.setLayout(jPanelBGControlarManutencao2Layout);
        jPanelBGControlarManutencao2Layout.setHorizontalGroup(
            jPanelBGControlarManutencao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGControlarManutencao2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBGControlarManutencao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnControleManutencao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovaControleManutencao, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelBGControlarManutencao2Layout.setVerticalGroup(
            jPanelBGControlarManutencao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGControlarManutencao2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnControleManutencao)
                .addGap(18, 18, 18)
                .addComponent(btnNovaControleManutencao)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        labelPreventiva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPreventiva.setForeground(new java.awt.Color(72, 61, 139));
        labelPreventiva.setText("Preventiva");

        labelPreventiva1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPreventiva1.setForeground(new java.awt.Color(72, 61, 139));
        labelPreventiva1.setText("Corretiva");

        labelOS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelOS.setForeground(new java.awt.Color(72, 61, 139));
        labelOS.setText("OS");

        labelData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelData.setForeground(new java.awt.Color(72, 61, 139));
        labelData.setText("Data");

        labelPreventiva4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPreventiva4.setForeground(new java.awt.Color(72, 61, 139));
        labelPreventiva4.setText("Situação");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 111, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelPreditiva)
                        .addGap(18, 18, 18)
                        .addComponent(txtPreventiva, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelQuilometragem)
                        .addGap(18, 18, 18)
                        .addComponent(txtQuilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelRenavam)
                        .addGap(18, 18, 18)
                        .addComponent(txtRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelPlaca)
                        .addGap(18, 18, 18)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelPreventiva1)
                            .addGap(18, 18, 18)
                            .addComponent(txtPreditiva1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelPreventiva)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtPreditiva, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(labelOS))
                                .addComponent(labelData, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtOS)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jPanelBGControlarManutencao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(35, 35, 35)
                                            .addComponent(jPanelBGControlarManutencao1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(labelPreventiva4)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtPreditiva4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGap(174, 174, 174))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPlaca))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRenavam)
                    .addComponent(txtRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtQuilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelQuilometragem))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPreventiva, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPreditiva))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPreditiva, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPreventiva))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPreditiva1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPreventiva1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelOS))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelData)
                    .addComponent(txtPreditiva4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPreventiva4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBGControlarManutencao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelBGControlarManutencao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarControleManutencao;
    private javax.swing.JButton btnControleManutencao;
    private javax.swing.JButton btnExcluirControleManutencao;
    private javax.swing.JButton btnNovaControleManutencao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBGControlarManutencao1;
    private javax.swing.JPanel jPanelBGControlarManutencao2;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelOS;
    private javax.swing.JLabel labelPlaca;
    private javax.swing.JLabel labelPreditiva;
    private javax.swing.JLabel labelPreventiva;
    private javax.swing.JLabel labelPreventiva1;
    private javax.swing.JLabel labelPreventiva4;
    private javax.swing.JLabel labelQuilometragem;
    private javax.swing.JLabel labelRenavam;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtOS;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPreditiva;
    private javax.swing.JTextField txtPreditiva1;
    private javax.swing.JTextField txtPreditiva4;
    private javax.swing.JTextField txtPreventiva;
    private javax.swing.JTextField txtQuilometragem;
    private javax.swing.JTextField txtRenavam;
    // End of variables declaration//GEN-END:variables
}
