/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpack;

import java.awt.Dimension;

/**
 *
 * @author Marcielli
 */
public class GerarRelatorioDeRodagem extends javax.swing.JInternalFrame {

    /**
     * Creates new form GerarRelatorioDeRodagem
     */
    public GerarRelatorioDeRodagem() {
        initComponents();
    }

    //Abrir jInternalFrame Centralizado
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelBGRelatorioDeEntrega2 = new javax.swing.JPanel();
        btnConsultarRelatorioDeRodagem = new javax.swing.JButton();
        btnImprimirRelatorioDeRodagem = new javax.swing.JButton();

        setClosable(true);
        setTitle("Gerar Relatório de Rodagem");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 61, 139)));
        jScrollPane1.setForeground(new java.awt.Color(72, 61, 139));

        jPanelBGRelatorioDeEntrega2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 61, 139), 1, true));
        jPanelBGRelatorioDeEntrega2.setForeground(new java.awt.Color(72, 61, 139));

        btnConsultarRelatorioDeRodagem.setBackground(new java.awt.Color(72, 61, 139));
        btnConsultarRelatorioDeRodagem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConsultarRelatorioDeRodagem.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarRelatorioDeRodagem.setText("Gerar Relatório");

        btnImprimirRelatorioDeRodagem.setBackground(new java.awt.Color(72, 61, 139));
        btnImprimirRelatorioDeRodagem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnImprimirRelatorioDeRodagem.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimirRelatorioDeRodagem.setText("Imprimir");

        javax.swing.GroupLayout jPanelBGRelatorioDeEntrega2Layout = new javax.swing.GroupLayout(jPanelBGRelatorioDeEntrega2);
        jPanelBGRelatorioDeEntrega2.setLayout(jPanelBGRelatorioDeEntrega2Layout);
        jPanelBGRelatorioDeEntrega2Layout.setHorizontalGroup(
            jPanelBGRelatorioDeEntrega2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGRelatorioDeEntrega2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBGRelatorioDeEntrega2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsultarRelatorioDeRodagem, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimirRelatorioDeRodagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelBGRelatorioDeEntrega2Layout.setVerticalGroup(
            jPanelBGRelatorioDeEntrega2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGRelatorioDeEntrega2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConsultarRelatorioDeRodagem)
                .addGap(18, 18, 18)
                .addComponent(btnImprimirRelatorioDeRodagem)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(872, Short.MAX_VALUE)
                .addComponent(jPanelBGRelatorioDeEntrega2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanelBGRelatorioDeEntrega2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarRelatorioDeRodagem;
    private javax.swing.JButton btnImprimirRelatorioDeRodagem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBGRelatorioDeEntrega2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
