/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpack;

/**
 *
 * @author Marcielli
 */
public class TelaInicio extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaInicio
     */
    public TelaInicio() {
        initComponents(); 
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpTelaInicio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        smCadastrar = new javax.swing.JMenu();
        imCliente = new javax.swing.JMenu();
        imClienteFisico = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        imClienteJuridico = new javax.swing.JMenuItem();
        jSeparator22 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        imFornecedor = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        imEquipamento = new javax.swing.JMenuItem();
        jSeparator23 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator24 = new javax.swing.JPopupMenu.Separator();
        imVeiculo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItem14 = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        jMenuItem16 = new javax.swing.JMenuItem();
        jSeparator20 = new javax.swing.JPopupMenu.Separator();
        jMenuItem17 = new javax.swing.JMenuItem();
        smConsultar = new javax.swing.JMenu();
        imConsultarCliente = new javax.swing.JMenu();
        imConsultarClienteFisico = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        imConsultarClienteJuridico = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        imConsultarFornecedor = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        imConsultarEquipamento = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        jMenuItem20 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        imConsultarVeiculo = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem18 = new javax.swing.JMenuItem();
        menuajuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator21 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator25 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator26 = new javax.swing.JPopupMenu.Separator();
        jMenuItem19 = new javax.swing.JMenuItem();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );

        jSeparator10.setForeground(new java.awt.Color(72, 61, 139));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(72, 61, 139));
        jLabel1.setText("  Copyright InoTec");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator10)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(8, 8, 8))
        );

        jdpTelaInicio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpTelaInicioLayout = new javax.swing.GroupLayout(jdpTelaInicio);
        jdpTelaInicio.setLayout(jdpTelaInicioLayout);
        jdpTelaInicioLayout.setHorizontalGroup(
            jdpTelaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdpTelaInicioLayout.setVerticalGroup(
            jdpTelaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        smCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder_add.png"))); // NOI18N
        smCadastrar.setText("Cadastrar");

        imCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/group_add.png"))); // NOI18N
        imCliente.setText("Cliente");
        imCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imClienteActionPerformed(evt);
            }
        });

        imClienteFisico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        imClienteFisico.setText("Físico");
        imClienteFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imClienteFisicoActionPerformed(evt);
            }
        });
        imCliente.add(imClienteFisico);
        imCliente.add(jSeparator5);

        imClienteJuridico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_suit.png"))); // NOI18N
        imClienteJuridico.setText("Jurídico");
        imClienteJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imClienteJuridicoActionPerformed(evt);
            }
        });
        imCliente.add(imClienteJuridico);

        smCadastrar.add(imCliente);
        smCadastrar.add(jSeparator22);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money_add.png"))); // NOI18N
        jMenu3.setText("Compras");

        imFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_add.png"))); // NOI18N
        imFornecedor.setText("Fornecedor");
        imFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imFornecedorActionPerformed(evt);
            }
        });
        jMenu3.add(imFornecedor);
        jMenu3.add(jSeparator3);

        imEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/application_put.png"))); // NOI18N
        imEquipamento.setText("Equipamento");
        imEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imEquipamentoActionPerformed(evt);
            }
        });
        jMenu3.add(imEquipamento);

        smCadastrar.add(jMenu3);
        smCadastrar.add(jSeparator23);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/chart_organisation.png"))); // NOI18N
        jMenuItem11.setText("Vendas e Serviços");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        smCadastrar.add(jMenuItem11);
        smCadastrar.add(jSeparator24);

        imVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/car_add.png"))); // NOI18N
        imVeiculo.setText("Veículo");
        imVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imVeiculoActionPerformed(evt);
            }
        });
        smCadastrar.add(imVeiculo);
        smCadastrar.add(jSeparator2);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/chart_bar_delete.png"))); // NOI18N
        jMenuItem5.setText("Contas a Pagar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        smCadastrar.add(jMenuItem5);
        smCadastrar.add(jSeparator4);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/chart_bar_add.png"))); // NOI18N
        jMenuItem6.setText("Contas a Receber");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        smCadastrar.add(jMenuItem6);
        smCadastrar.add(jSeparator11);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lorry_add.png"))); // NOI18N
        jMenuItem14.setText("Cargas");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        smCadastrar.add(jMenuItem14);
        smCadastrar.add(jSeparator18);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/application_cascade.png"))); // NOI18N
        jMenuItem15.setText("Volumes");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        smCadastrar.add(jMenuItem15);
        smCadastrar.add(jSeparator19);

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/group_add.png"))); // NOI18N
        jMenuItem16.setText("Funcionário");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        smCadastrar.add(jMenuItem16);
        smCadastrar.add(jSeparator20);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        jMenuItem17.setText("Usuário");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        smCadastrar.add(jMenuItem17);

        jMenuBar1.add(smCadastrar);

        smConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder_explore.png"))); // NOI18N
        smConsultar.setText("Consultar");

        imConsultarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/group.png"))); // NOI18N
        imConsultarCliente.setText("Cliente");

        imConsultarClienteFisico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        imConsultarClienteFisico.setText("Físico");
        imConsultarClienteFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imConsultarClienteFisicoActionPerformed(evt);
            }
        });
        imConsultarCliente.add(imConsultarClienteFisico);
        imConsultarCliente.add(jSeparator9);

        imConsultarClienteJuridico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_suit.png"))); // NOI18N
        imConsultarClienteJuridico.setText("Jurídico");
        imConsultarClienteJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imConsultarClienteJuridicoActionPerformed(evt);
            }
        });
        imConsultarCliente.add(imConsultarClienteJuridico);

        smConsultar.add(imConsultarCliente);
        smConsultar.add(jSeparator1);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money_dollar.png"))); // NOI18N
        jMenu4.setText("Compras");

        imConsultarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        imConsultarFornecedor.setText("Fornecedor");
        imConsultarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imConsultarFornecedorActionPerformed(evt);
            }
        });
        jMenu4.add(imConsultarFornecedor);
        jMenu4.add(jSeparator12);

        imConsultarEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/application.png"))); // NOI18N
        imConsultarEquipamento.setText("Equipamento");
        imConsultarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imConsultarEquipamentoActionPerformed(evt);
            }
        });
        jMenu4.add(imConsultarEquipamento);

        smConsultar.add(jMenu4);
        smConsultar.add(jSeparator15);

        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/chart_curve_go.png"))); // NOI18N
        jMenuItem20.setText("Vendas e Serviços");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        smConsultar.add(jMenuItem20);
        smConsultar.add(jSeparator6);

        imConsultarVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/car.png"))); // NOI18N
        imConsultarVeiculo.setText("Veículo");
        imConsultarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imConsultarVeiculoActionPerformed(evt);
            }
        });
        smConsultar.add(imConsultarVeiculo);
        smConsultar.add(jSeparator7);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/chart_bar_delete.png"))); // NOI18N
        jMenuItem7.setText("Contas a Pagar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        smConsultar.add(jMenuItem7);
        smConsultar.add(jSeparator16);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/chart_bar_add.png"))); // NOI18N
        jMenuItem8.setText("Contas a Receber");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        smConsultar.add(jMenuItem8);
        smConsultar.add(jSeparator13);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/compress.png"))); // NOI18N
        jMenuItem12.setText("Cargas e Volumes");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        smConsultar.add(jMenuItem12);

        jMenuBar1.add(smConsultar);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/application_double.png"))); // NOI18N
        jMenu1.setText("Controle");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lorry_error.png"))); // NOI18N
        jMenuItem9.setText("Manutenção");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);
        jMenu1.add(jSeparator14);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lorry_go.png"))); // NOI18N
        jMenuItem13.setText("Saída de Carga");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem13);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/database_table.png"))); // NOI18N
        jMenu2.setText("Relatório");

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book.png"))); // NOI18N
        jMenuItem10.setText("Rodagem");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);
        jMenu2.add(jSeparator8);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_go.png"))); // NOI18N
        jMenuItem18.setText("Entrega");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem18);

        jMenuBar1.add(jMenu2);

        menuajuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/help.png"))); // NOI18N
        menuajuda.setText("Ajuda");
        menuajuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuajudaActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/information.png"))); // NOI18N
        jMenuItem1.setText("Sobre TransPack");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuajuda.add(jMenuItem1);
        menuajuda.add(jSeparator17);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder_add.png"))); // NOI18N
        jMenuItem2.setText("Como Cadastrar?");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuajuda.add(jMenuItem2);
        menuajuda.add(jSeparator21);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder_explore.png"))); // NOI18N
        jMenuItem3.setText("Como Consultar?");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuajuda.add(jMenuItem3);
        menuajuda.add(jSeparator25);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder_key.png"))); // NOI18N
        jMenuItem4.setText("Como Recuperar Senha?");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuajuda.add(jMenuItem4);
        menuajuda.add(jSeparator26);

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/telephone.png"))); // NOI18N
        jMenuItem19.setText("Entre em Contato");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        menuajuda.add(jMenuItem19);

        jMenuBar1.add(menuajuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpTelaInicio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpTelaInicio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imVeiculoActionPerformed
        CadastrarVeiculo obj=new CadastrarVeiculo();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_imVeiculoActionPerformed

    private void imFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imFornecedorActionPerformed
        CadastrarFornecedor obj=new CadastrarFornecedor();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    
    }//GEN-LAST:event_imFornecedorActionPerformed

    private void imEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imEquipamentoActionPerformed
        CadastrarEquipamento obj=new CadastrarEquipamento();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_imEquipamentoActionPerformed

    private void imClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imClienteActionPerformed
        CadastrarClienteFisico obj=new CadastrarClienteFisico();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_imClienteActionPerformed

    private void imClienteJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imClienteJuridicoActionPerformed
        CadastrarClienteJuridico obj=new CadastrarClienteJuridico();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_imClienteJuridicoActionPerformed

    private void imConsultarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imConsultarVeiculoActionPerformed
        ConsultarVeiculo obj=new ConsultarVeiculo();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_imConsultarVeiculoActionPerformed

    private void imConsultarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imConsultarFornecedorActionPerformed
        ConsultarFornecedor obj=new ConsultarFornecedor();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_imConsultarFornecedorActionPerformed

    private void imConsultarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imConsultarEquipamentoActionPerformed
        ConsultarEquipamento obj=new ConsultarEquipamento();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_imConsultarEquipamentoActionPerformed

    private void imConsultarClienteFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imConsultarClienteFisicoActionPerformed
        ConsultarClienteFisico obj=new ConsultarClienteFisico();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_imConsultarClienteFisicoActionPerformed

    private void imConsultarClienteJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imConsultarClienteJuridicoActionPerformed
        ConsultarClienteJuridico obj=new ConsultarClienteJuridico();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_imConsultarClienteJuridicoActionPerformed

    private void imClienteFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imClienteFisicoActionPerformed
        CadastrarClienteFisico obj=new CadastrarClienteFisico();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
        
    }//GEN-LAST:event_imClienteFisicoActionPerformed

    private void menuajudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuajudaActionPerformed
      
    }//GEN-LAST:event_menuajudaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        SobreTransPack obj=new SobreTransPack();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ComoCadastrar obj= new ComoCadastrar();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ComoConsultar obj= new ComoConsultar();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ComoRecuperarSenha obj=new ComoRecuperarSenha();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        CadastrarContasAPagar obj=new CadastrarContasAPagar();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        CadastrarContasAReceber obj=new CadastrarContasAReceber();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        ConsultarContasAPagar obj=new ConsultarContasAPagar();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        ConsultarContasAReceber obj=new ConsultarContasAReceber();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        ControlarManutencao obj=new ControlarManutencao();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        GerarRelatorioDeRodagem obj=new GerarRelatorioDeRodagem();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        CadastrarVendasEServicos obj=new CadastrarVendasEServicos();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        ConsultarCargasEVolumes obj=new ConsultarCargasEVolumes();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        ControlarSaidaDeCarga obj=new ControlarSaidaDeCarga();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        CadastrarCarga obj=new CadastrarCarga();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        CadastrarVolumes obj=new CadastrarVolumes();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        CadastrarFuncionarios obj=new CadastrarFuncionarios();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        CadastrarUsuario obj=new CadastrarUsuario();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        GerarRelatorioDeEntrega obj=new GerarRelatorioDeEntrega();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        EntreEmContato obj=new EntreEmContato();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        ConsultarVendasEServicos obj=new ConsultarVendasEServicos();
        jdpTelaInicio.add(obj);
        obj.setVisible(true);
        obj.setPosicao();
    }//GEN-LAST:event_jMenuItem20ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu imCliente;
    private javax.swing.JMenuItem imClienteFisico;
    private javax.swing.JMenuItem imClienteJuridico;
    private javax.swing.JMenu imConsultarCliente;
    private javax.swing.JMenuItem imConsultarClienteFisico;
    private javax.swing.JMenuItem imConsultarClienteJuridico;
    private javax.swing.JMenuItem imConsultarEquipamento;
    private javax.swing.JMenuItem imConsultarFornecedor;
    private javax.swing.JMenuItem imConsultarVeiculo;
    private javax.swing.JMenuItem imEquipamento;
    private javax.swing.JMenuItem imFornecedor;
    private javax.swing.JMenuItem imVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator20;
    private javax.swing.JPopupMenu.Separator jSeparator21;
    private javax.swing.JPopupMenu.Separator jSeparator22;
    private javax.swing.JPopupMenu.Separator jSeparator23;
    private javax.swing.JPopupMenu.Separator jSeparator24;
    private javax.swing.JPopupMenu.Separator jSeparator25;
    private javax.swing.JPopupMenu.Separator jSeparator26;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JDesktopPane jdpTelaInicio;
    private javax.swing.JMenu menuajuda;
    private javax.swing.JMenu smCadastrar;
    private javax.swing.JMenu smConsultar;
    // End of variables declaration//GEN-END:variables
}
