/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpack;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcielli
 */
public class TelaCadastrar extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastrar
     */
    public TelaCadastrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCadastrar = new javax.swing.JPanel();
        labelInicioContrato = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        labelCargo = new javax.swing.JLabel();
        labelRG = new javax.swing.JLabel();
        labelCPF = new javax.swing.JLabel();
        labelFimContrato = new javax.swing.JLabel();
        labelCel = new javax.swing.JLabel();
        labeTel = new javax.swing.JLabel();
        btnCadastrarFuncionario = new javax.swing.JButton();
        btnNovoCadastrarFuncionario = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtRG1 = new javax.swing.JFormattedTextField();
        txtCPF = new javax.swing.JFormattedTextField();
        txtInicioContrato = new javax.swing.JFormattedTextField();
        txtFimContrato = new javax.swing.JFormattedTextField();
        txtCel = new javax.swing.JFormattedTextField();
        txtTel = new javax.swing.JFormattedTextField();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();

        setClosable(true);
        setResizable(true);
        setTitle("Cadastro Funcionário");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelInicioContrato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelInicioContrato.setForeground(new java.awt.Color(72, 61, 139));
        labelInicioContrato.setText("Inicio Contrato");

        labelNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNome.setForeground(new java.awt.Color(72, 61, 139));
        labelNome.setText("Nome");

        labelCargo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCargo.setForeground(new java.awt.Color(72, 61, 139));
        labelCargo.setText("Cargo");

        labelRG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelRG.setForeground(new java.awt.Color(72, 61, 139));
        labelRG.setText("RG");

        labelCPF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCPF.setForeground(new java.awt.Color(72, 61, 139));
        labelCPF.setText("CPF");

        labelFimContrato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelFimContrato.setForeground(new java.awt.Color(72, 61, 139));
        labelFimContrato.setText("Fim Contrato");

        labelCel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCel.setForeground(new java.awt.Color(72, 61, 139));
        labelCel.setText("Cel");

        labeTel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeTel.setForeground(new java.awt.Color(72, 61, 139));
        labeTel.setText("Tel");

        btnCadastrarFuncionario.setBackground(new java.awt.Color(72, 61, 139));
        btnCadastrarFuncionario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastrarFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarFuncionario.setText("Cadastrar");
        btnCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFuncionarioActionPerformed(evt);
            }
        });

        btnNovoCadastrarFuncionario.setBackground(new java.awt.Color(72, 61, 139));
        btnNovoCadastrarFuncionario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNovoCadastrarFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoCadastrarFuncionario.setText("Novo Cadastro");
        btnNovoCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCadastrarFuncionarioActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Secretária", "Atendente", "Encarregado" }));

        try {
            txtRG1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtInicioContrato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtFimContrato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(72, 61, 139));
        lblSenha.setText("Senha");

        javax.swing.GroupLayout panelCadastrarLayout = new javax.swing.GroupLayout(panelCadastrar);
        panelCadastrar.setLayout(panelCadastrarLayout);
        panelCadastrarLayout.setHorizontalGroup(
            panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarLayout.createSequentialGroup()
                .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadastrarLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(labelRG)
                        .addGap(18, 18, 18)
                        .addComponent(txtRG1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(labelCPF)
                        .addGap(18, 18, 18)
                        .addComponent(txtCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarLayout.createSequentialGroup()
                        .addContainerGap(224, Short.MAX_VALUE)
                        .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarLayout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addGap(19, 19, 19)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarLayout.createSequentialGroup()
                                .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelInicioContrato, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelCargo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelCel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCadastrarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnNovoCadastrarFuncionario))
                                    .addGroup(panelCadastrarLayout.createSequentialGroup()
                                        .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jComboBox1, 0, 241, Short.MAX_VALUE)
                                            .addComponent(txtInicioContrato)
                                            .addComponent(txtCel))
                                        .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(panelCadastrarLayout.createSequentialGroup()
                                                .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(panelCadastrarLayout.createSequentialGroup()
                                                        .addGap(31, 31, 31)
                                                        .addComponent(labelFimContrato))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarLayout.createSequentialGroup()
                                                        .addGap(102, 102, 102)
                                                        .addComponent(labeTel)))
                                                .addGap(18, 18, 18)
                                                .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtFimContrato)
                                                    .addComponent(txtTel, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)))
                                            .addGroup(panelCadastrarLayout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addComponent(lblSenha)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                .addContainerGap())
        );
        panelCadastrarLayout.setVerticalGroup(
            panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarLayout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadastrarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelCPF))
                    .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelRG)
                        .addComponent(txtRG1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelInicioContrato)
                            .addGroup(panelCadastrarLayout.createSequentialGroup()
                                .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelCargo)
                                    .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblSenha)
                                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelCadastrarLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(labelFimContrato))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFimContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtInicioContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCadastrarLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(labeTel))
                            .addGroup(panelCadastrarLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCel)
                        .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarFuncionario)
                .addGap(17, 17, 17)
                .addComponent(btnNovoCadastrarFuncionario)
                .addGap(124, 124, 124))
        );

        getContentPane().add(panelCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 600));

        setBounds(0, 0, 1057, 622);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCadastrarFuncionarioActionPerformed
        // limpa tela 
       txtNome.setText("");
       txtCPF.setText("");
     //  txtCargo.setText("");
       txtCel.setText("");
       txtInicioContrato.setText("");
       txtFimContrato.setText("");
       txtRG1.setText("");
       txtTel.setText("");
       txtSenha.setText(""); //marci
       
       
    }//GEN-LAST:event_btnNovoCadastrarFuncionarioActionPerformed

    private void btnCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFuncionarioActionPerformed
//faz conexão com o driver
        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.print("Driver Conectado");
        //variavel de conecção
        Connection con;
        con = DriverManager.getConnection( "jdbc:mysql://127.0.0.1/transpack","root","");
        //insere valor no banco
        String query = "INSERT INTO cadastrarusuario (nome,rg,cpf,cargo,senha,inicio_contrato,fim_contrato,cel,tel) VALUES (?,?,?,?,?,?,?,?,?)";
        //prepara a entrada de dados
        PreparedStatement stmt = (PreparedStatement) con.prepareStatement(query);

        //pega os valores para inserção
        
        stmt.setString(1,txtNome.getText());
        stmt.setString(2, txtRG1.getText());
        stmt.setString(3, txtCPF.getText());
        stmt.setString(4, (String) jComboBox1.getSelectedItem());
        stmt.setString(5, txtSenha.getText());
        stmt.setString(6, txtInicioContrato.getText());
        stmt.setString(7, txtFimContrato.getText());
        stmt.setString(8, txtCel.getText());
        stmt.setString(9, txtTel.getText());
        
                           
      JOptionPane.showInputDialog("Salvo");
        

        //atualiza os dados
        stmt.executeUpdate();
        
        //fecha conexão
        stmt.close();
        con.close();
        
               
        
        
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        System.out.print("Falha na conexão com Driver");
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        //catch de conexão com banco de dados
        System.out.print("Erro de conexão com Banco de dados");
        }       
    }//GEN-LAST:event_btnCadastrarFuncionarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarFuncionario;
    private javax.swing.JButton btnNovoCadastrarFuncionario;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel labeTel;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelCel;
    private javax.swing.JLabel labelFimContrato;
    private javax.swing.JLabel labelInicioContrato;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelRG;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPanel panelCadastrar;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtCel;
    private javax.swing.JFormattedTextField txtFimContrato;
    private javax.swing.JFormattedTextField txtInicioContrato;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtRG1;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JFormattedTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
